### ISSUE TITLE
feature request: Add support for switching the iniative of dead pcs to just before whatever dropped them

### ISSUE THREAD

**Issue by xdy** [xdy/xdy-pf2e-workbench#10]
I.e. in the damage-applying code or thereabouts, check if hp went below 0, if so change initiative to 'just before current initiative'. Does depend on the GM applying damage during the correct initiative, but, good enough I think.

**Comment by shemetz** [comment]
Make it a rightclick context menu option in the initiative tracker, not just a keybinding!

**Comment by xdy** [comment]
Heh. I forgot to close this issue in the commit that added a keybind, so, I guess I'll close it when the context menu option exists.
Or if/when I figure out how to listen to dead people - ok, combatants being killed in foundry. :)

**Comment by xdy** [comment]
Context menu added (behind a setting), now to figure out how to catch dying souls before Pharasma does... :)

**Comment by JamzTheMan** [comment]
Is it possible to auto move PC? maybe triggered on 0 health or adding Dying condition?

Hmm, or maybe we just need a single keybind that marks/adds dying AND moves init?

BTW, just discovered your module, nice work!

**Comment by xdy** [comment]
Hello fellow (former?) MapTool developer!
And, yep, that is what my previous post about catching dying souls is about. :)
I *think* I can do it in preUpdateActor without too much hassle, but haven't had a chance to really look into it yet.
I don't want to track any state in this module. Fire and forget or not at all...

**Comment by xdy** [comment]
It turned out to be as easy as it looked, so, closing this feature request with release 2.11.0 which is currently building.

**Comment by xdy** [comment]
Well, almost as easy as it looked. But, fixed in 2.11.1

**Comment by JamzTheMan** [comment]
Noice!
