### ISSUE TITLE
Testing Bug Reporter

### ISSUE THREAD

**Issue by leagueoffoundryvttdevs** [xdy/xdy-pf2e-workbench#100]
**Core:** 9.245
**System:** pf2e v3.3.0
**Module Version:** xdy-pf2e-workbench v2.21.8
 
**Description**:
If this issue is open, close it. :)<details>
<summary>Active Modules</summary>

babele--v2.2.3;
bug-reporter--v1.3.2;
dice-so-nice--v4.3.0;
fr-core--v9.245.0;
lang-fr-pf2e--v3.3.0;
lang-sv--v1.0.1;
lib-wrapper--v1.11.1.0;
module-credits--v1.0.0;
pf2e-tweaks--v0.6.1;
tidy-ui_game-settings--v0.1.29;
xdy-pf2e-workbench--v2.21.8;
</details><details>
<summary>Additional Details</summary>

undefined
</details>

**Comment by xdy** [comment]
As this issue is open, I am closing it. A bit amusing that it turned out to be issue #100 :)
