### ISSUE TITLE
{Update}[Another Alternative Bonus progression] 1.3

### ISSUE THREAD

**Issue by NotReallyACat** [xdy/xdy-pf2e-workbench#1005]
@xdy Heyo, huge thanks for including this in your workbench module. 

I have done an update

[AABP1.3.zip](https://github.com/xdy/xdy-pf2e-workbench/files/12826258/AABP1.3.zip)

---

Changelog:
- Added a proper description
- Created additional effects for variety of playstyles
- When feat is added to character choice set presented with which variant rule you want
- Images for the feat and all effects (made by me no licence free for public use)
- Created a github page so people can post feedback and issue there (https://github.com/CrackJackFlood/pf2e-aabp) links are included in the items description.

---

Images:
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/49882452/0933cc51-eb10-4bf5-abec-ee9fe701a367)
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/49882452/39d9ab1e-9739-4b28-8e75-1b980d3f462c)
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/49882452/342409ea-1d7e-44b4-aea5-0e384f8138ef)
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/49882452/a21729bd-869e-4635-b573-268aff3a0989)
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/49882452/5870d9af-078d-418e-b1ad-2c9f998372ab)
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/49882452/7807b06d-b4e7-407d-8274-db244b30521f)

Please let me know of any improvements I can make.

**Comment by NotReallyACat** [comment]
#999 Update for this

**Comment by NotReallyACat** [comment]
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/49882452/700a616a-ca21-4635-949f-ad7c9c206a77)

1.2 update added scaling for the deadly trait

**Comment by NotReallyACat** [comment]
[AABP1.3.zip](https://github.com/xdy/xdy-pf2e-workbench/files/12826259/AABP1.3.zip)

1.3 update converted all effects to feats that are set as deity curses should make it harder to accidently delete

**Comment by xdy** [comment]
Included in 5.20.1
