### ISSUE TITLE
House Rules setting not applying saves for hammer and flail critical specialisations

### ISSUE THREAD

**Issue by pedrogrullada** [xdy/xdy-pf2e-workbench#1018]
Unless I'm misunderstanding what the house rule is supposed to be, it doesn't seem like the critical specialisation is being modified by the module. Considering it will be RAW in a little over a month it may not be worth fixing, but I really wanted to implement it before that

![image](https://github.com/xdy/xdy-pf2e-workbench/assets/103401186/c10fd269-bf23-4b44-b899-ede39cc28430)

Foundry 313, PF2e 5.6.2, Workbench 5.22.0

**Comment by xdy** [comment]
Yeah, I'll just remove that option. To quote the discord:
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/246024/77ac06cc-4c0c-44a5-ba95-e6c9d13ff456)
:)
