### ISSUE TITLE
Advanced Countdown not saving new presets

### ISSUE THREAD

**Issue by Simyonovich** [xdy/xdy-pf2e-workbench#1019]
When I open the Advanced Countdown macro, it refuses to save new presets, even though I have pressed save. It appears to be saved after the preset has been entered and saved, but as soon as I close the macro and then reopen, the saved presets have been wiped, except for the first two entries.

**Comment by xdy** [comment]
This macro is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Advanced%20Countdown.js
Ping Symon about it on https://discord.com/channels/880968862240239708/880969174661353484 or make an issue on Symon's repo.

**Comment by Simyonovich** [comment]
Ok, thank's for you response. I will do that.
