### ISSUE TITLE
Refocus macro broken

### ISSUE THREAD

**Issue by weepingminotaur** [xdy/xdy-pf2e-workbench#1022]
Not sure when this cropped up, but I think it happened in one of the recent releases from Oct. 06. Trying to run the refocus macro produces this error. 
<img width="560" alt="Screenshot 2023-10-12 at 9 30 18 AM" src="https://github.com/xdy/xdy-pf2e-workbench/assets/90105219/552171b8-3e16-41f5-bb03-dfaa951cc810">

**Comment by WizardForHire123** [comment]
If it helps @xdy it looks like the customizable version is still working, but and I could be wrong here/may not have been there to begin with but it looks to be absent in the `donotimport folders`.

**Comment by xdy** [comment]
Ah, a system update (presumably to support remaster) broke the function I used. Given how close the remaster is I don't think I'll be fixing it. Especially as running the following once you have a selected token works in the latest system version to give back all focus:
```
_token.actor?.spellcasting.refocus({ all: true });
```
Or like this for 'all selected tokens':
```
canvas.tokens.controlled.forEach(x=>x.actor.spellcasting.refocus({all:true}))
```
Instead, I'll remove the refocus macro. (But I'll keep the customizable one as that apparently works. It, incidentally, has never been in the donotimport folder, only the ones from Symon's repo are there.)
