### ISSUE TITLE
Spells not private when they have varient damage rules

### ISSUE THREAD

**Issue by demotech89** [xdy/xdy-pf2e-workbench#1024]
I have tried a few spells and most are hidden when I have the option in the workbench selected as shown in image below.

![image1](https://github.com/xdy/xdy-pf2e-workbench/assets/147771452/524c2fe7-13cc-4291-a9d1-037b40fe1a90)

However, if a spell has varient damage types such as Teleknitic Projectile from Pathfinder 2e, as below,

![image2](https://github.com/xdy/xdy-pf2e-workbench/assets/147771452/6a8bdc90-dbe5-463d-b205-67a33e750133)

then the spell will show up to all players as shown below

![image3](https://github.com/xdy/xdy-pf2e-workbench/assets/147771452/8a9a8da4-613f-45f2-a739-78cf411fe918)
![image4](https://github.com/xdy/xdy-pf2e-workbench/assets/147771452/3ed0de97-94fe-4897-bea5-d3c13a17ac84)

I tested it with other spells such as Divine Lance from PF2e and it is doing the same. It seems to not hide spells that have various options for damage. 
![image5](https://github.com/xdy/xdy-pf2e-workbench/assets/147771452/c1ca322f-4e2a-4ef0-954b-7b2ddb1e5010)

**Comment by xdy** [comment]
For now a workaround is to switch to Private GM roll before clicking the variant button.

**Comment by xdy** [comment]
This was fixed a long time ago, in commit 56a0342ad27ba4f2ea956a7dc4929dc7cebf6621
