### ISSUE TITLE
Stunned is removed rather than reduced by 1.

### ISSUE THREAD

**Issue by WaterpoloBlock** [xdy/xdy-pf2e-workbench#1027]
Foundry Version: 11

Build: 308

Game System: Pf2e (5.6.2)

Active Modules:
PF2e WorkBench
The Forge

The issue: If I go into the settings -> PF2e Workbench -> Manage World Automation Settings -> And check the box for "Automatically Reduce Stunned on turn Start."

Now [RAW](https://2e.aonprd.com/Conditions.aspx?ID=36), if stunned has a numeric value. The numeric value of Stunned is reduced by 1. There are exceptions to the rule.

However, when initiative has been rolled and the encounter is running. Once it is the turn for the PC/NPC who has the stunned condition. The system will remove all values of stunned from it. Even if the stunned value is greater then 1.

When in reality, it should reduce it by 1. Not outright remove it. Unless of course the NPC/PC has a stunned value of 1.

**Comment by xdy** [comment]
Seems to work for me (using foundry 11.313, pf2e 5.7.2 and workbench 5.23.4). I gave an actor Stunned 10, each turn it reduces it by three, i.e. one per action the actor would have regained. If I give the actor Quickened, it reduces Stunned by four each turn. (Until running out of Stunned.)

**Comment by WaterpoloBlock** [comment]
I'll be able to test in a few hours and let you know.

**Comment by WaterpoloBlock** [comment]
Issue is still there. I have tried it on two separate computers on Chrome, Brave and Fire Fox. No change.

It appears to be reducing Stunned by -3 each turn.

[Here is a video of it](https://drive.google.com/file/d/1Akt5GWq57xDcmSXm_PYMAp9Ugs6Ocqs4/view?usp=sharing), mute the volume. I forgot to mute my mic, so it just recorded me clicking and dead air.

**Comment by xdy** [comment]
Ah, ok. Yeah, that is the way it's supposed to work according to the rules.
To quote from https://2e.aonprd.com/Conditions.aspx?ID=36, "Each time you regain actions (such as at the start of your turn), reduce the number you regain by your stunned value, then reduce your stunned value by the number of actions you lost.".
E.g. if your have, say, Stunned 5, it'll lower Stunned by 3 the first turn (as that is the number of actions you would regain), and finally by 2 on the second turn, after which you are no longer affected by Stunned. (If you were also Quickened (and thus would regain 4 actions), it will lower Stunned by 4 the first turn and 1 the second turn.)

**Comment by WaterpoloBlock** [comment]
Oh wow, I’ve been invoking this rule wrong this whole time. That's my fault, sorry.

You can close the ticket.
