### ISSUE TITLE
Treat wounds Macro doesn't run when using both Risky Surgery and Assurance

### ISSUE THREAD

**Issue by xlii1356** [xdy/xdy-pf2e-workbench#1028]
When running the Treat Wounds and Battle Medicine Macro, if you select both assurance and risky surgery, it displays in chat that you succeed, but it that's it, no healing dice, no damage dice, and to Treat wounds immunity

**Comment by xdy** [comment]
This macro is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Treat%20Wounds%20and%20Battle%20Medicine.js
Ping darkim about it on https://discord.com/channels/880968862240239708/880969174661353484 or make an issue on Symon's repo.
