### ISSUE TITLE
[BUG] NPC mystification setting "Use elite/weak status" is not working v10/v11

### ISSUE THREAD

**Issue by Br0ken-0ne** [xdy/xdy-pf2e-workbench#1030]
Even if the toggle is set and the creatures elite/weak status is set it does not change anything for the created mystified name.

I could reproduce this on latest v10 (303) with latest PF2E setting 4.12.9 and the latest v10 module. Someone on discord tried it on v11 (unkown exact versions) and it seems to be bugged there, too.

**Comment by esheyw** [comment]
can confirm this is also not working in workbench 5.23.1.
