### ISSUE TITLE
Changing client settings pauses game for player, GM cannot see that it is happening

### ISSUE THREAD

**Issue by boloniusMonk** [xdy/xdy-pf2e-workbench#1032]
When a player uses Manage Client Automation Settings, it pauses the game for them upon change.  As the GM, I have no indication that this has happened.  I can unpause them by pausing and unpausing the game, but there is no way for me to know without the player telling me.   I am not sure if this is intended behaviour, or if there is a setting to disable it.

**Comment by xdy** [comment]
I haven't been able to reproduce this, does it still happen on the latest versions of everything? (I.e. foundry 11.315, pf2e 5.8.3, workbench 5.27.12)

**Comment by boloniusMonk** [comment]
I am not able to replicate after having updated.
