### ISSUE TITLE
Empty settings set to null on save

### ISSUE THREAD

**Issue by WesBelmont** [xdy/xdy-pf2e-workbench#107]
When saving settings, all the entries that contain empty strings are set to "null" instead of empty.
This is causing mystification to result in "Null Animal 10" instead of the expected "Animal 10"

Manually changing the settings in settings.db to the empty string resolves the issue temporarily.

**Comment by xdy** [comment]
Hmm. I can't get this to happen.  I tried various combinations of checkboxes, with some or all text fields set to "", but never got it to display null.
Could you add a screenshot of your settings when it happens for you?
Also, what versions of the module, found and browser are you using?

**Comment by WesBelmont** [comment]
It appears to be caused by [token-health](https://github.com/schlosrat/token-health). I'm trying to find out why it is causing the behaviour. I'll submit a bug report on their project.
