### ISSUE TITLE
[BUG] "Do not disable item bonuses when using ABP" option no longer working

### ISSUE THREAD

**Issue by AFigureOfBlue** [xdy/xdy-pf2e-workbench#1078]
The "Do not disable item bonuses when using ABP" option no longer seems to be working; item bonuses (at least to skills and to speed) aren't getting applied even when it is checked. Tested on a new empty world with only this module installed; the "ABP: Allow Property Runes" setting in the system; Foundry version 11 build 308; PF2e system 5.8.3; and PF2e Workbench 5.18.2.

**Comment by xdy** [comment]
Unfortunately I can't figure out how to fix it (it's been broken for months), so I'm removing this feature. I recommend you instead use https://github.com/reonZ/pf2e-toolbelt/#automatic-rune-progression-requires-reload to handle ABP.

**Comment by AFigureOfBlue** [comment]
For what it's worth, this feature was working for me as of just a couple weeks ago (I'm not sure the exact version numbers, but I generally update modules and such weekly), so it does seem like it must have been a relatively recent change to either the module or the system, not something from months ago. It was definitely working as of October 23 because I filed an unrelated bug reporton the PF2e system ( https://github.com/foundryvtt/pf2e/issues/10887 ) with the same settings in place and the item bonuses were applying then. I don't know if that timeframe information may be able to help with debugging.
