### ISSUE TITLE
Mystifying Tokens no longer works with PF2 Remaster Update

### ISSUE THREAD

**Issue by demotech89** [xdy/xdy-pf2e-workbench#1089]
Hey just wanted to make you aware since I absolutely love the work you do on PF2e Workbench, but I noticed after updating to the remaster PF2 rules in foundry, I am no longer able to mystify tokens. The eye symbol is on the token but clicking it does nothing. Alt dragging it to the scene also no longer mystifies the token either. From what I can see, items are still able to be mystified.

**Comment by xdy** [comment]
Give it another try with the latest release (5.29.0), it Works On My Machine.

**Comment by demotech89** [comment]
100% working on my end now. That was a very quick turn around!
