### ISSUE TITLE
Macros : Healer's tools

### ISSUE THREAD

**Issue by Araluen124** [xdy/xdy-pf2e-workbench#1091]
The Treat wounds and Battle medecine macro doesn't recognise the healer's tools with the new update

**Comment by xdy** [comment]
This macro is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Treat%20Wounds%20and%20Battle%20Medicine.js
Ping darkim about it on https://discord.com/channels/880968862240239708/880969174661353484 or make an issue on Symon's repo.
