### ISSUE TITLE
Update text for Refocus exploration activity

### ISSUE THREAD

**Issue by Failtier** [xdy/xdy-pf2e-workbench#1095]
Hi,
I noticed that the Refocus text isn't updated yet. The new text is as follows (PC, p. 298):

> **Requirements** You have a focus pool.
> -
> You spend 10 minutes performing deeds to restore your magical connection. This restores 1 Focus Point to your focus pool. The deeds you need to perform are specified in the class or ability that gives you your focus spells. These deeds can usually overlap with other tasks that relate to the source of your focus spells. For instance, a cleric with focus spells from a holy deity can usually Refocus while tending the wounds of their allies.

**Comment by xdy** [comment]
This has been updated in the system since this issue was made, so closing.
