### ISSUE TITLE
Add setting for reyzors private spells - i.e remove save on workbench chat card

### ISSUE THREAD

**Issue by GuitarGuyNick** [xdy/xdy-pf2e-workbench#1097]
when you cast a private spells using reyzors action engine it produces the save result for the pcs to be referenced for the results of the spell. but also there is a save coming at the end of workbenches chat card. i was wondering if in workbench there could be a setting to remove the save from workbenches chat card to avoid clicking the wrong save needed.

**Comment by xdy** [comment]
Done in 5.60.0 (it's automatically removed if pf2e target helper is enabled).

**Comment by GuitarGuyNick** [comment]
thanks!
