### ISSUE TITLE
BAM doesn't reconize the renamed healer's toolkit as healer's tools

### ISSUE THREAD

**Issue by JeanVictorL** [xdy/xdy-pf2e-workbench#1098]
the healer's tools item was renamed to healer's toolkit and when using the Basic Actions Macro, it says that the character doesn't have healer's tools in the inventory.

**Comment by xdy** [comment]
BAM uses a macro that is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Treat%20Wounds%20and%20Battle%20Medicine.js
Ping darkim about it on https://discord.com/channels/880968862240239708/880969174661353484 or make an issue on Symon's repo.
