### ISSUE TITLE
Spellstrike macro doesn't work anymore

### ISSUE THREAD

**Issue by cyanogreen** [xdy/xdy-pf2e-workbench#1100]
some parts of it appear to do, it still checks for targeting but if you do have something targeted the macro just doesn't do anything.

**Comment by xdy** [comment]
This macro is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Spellstrike.js
Symon knows about the issue though, (https://discord.com/channels/880968862240239708/1116034857907273832/1175250957886574704)
