### ISSUE TITLE
BA Macro Fix - change Aid from Effect link to Action function

### ISSUE THREAD

**Issue by apoapostolov** [xdy/xdy-pf2e-workbench#1102]
Can you please change Aid in BA macro to the new Aid function? Aid, when I configured the macro before it was added to Workbench, is linked to the effect, not the action. This makes it useful for a GM, but counter-intuitive to players because instead of the Aider, the Aided has to mark themselves with the effect. By switching to the function, the Aider can now fire Aid and mods can automate this further.

**Comment by xdy** [comment]
I instead added direct support for calling the ASE macro if that module is active.

**Comment by apoapostolov** [comment]
Much better. Thank you!
