### ISSUE TITLE
Spellstrike Macro not working since system update

### ISSUE THREAD

**Issue by dbfimau83** [xdy/xdy-pf2e-workbench#1105]
The Spellstrike macro for the Magus from the "Symon-provided macros" folder does not seem to be working any longer, at least for me. Prior to the recent PF2e system update it worked wonderfully, but nothing happens when I attempt to use it while running the latest versions of the system and workbench.

Thanks so much for all your work!

**Comment by xdy** [comment]
This macro is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Spellstrike.js
Symon knows about the issue though, (https://discord.com/channels/880968862240239708/1116034857907273832/1175250957886574704)
