### ISSUE TITLE
BAM Squeeze Macro Should Require Trained in Acrobatics

### ISSUE THREAD

**Issue by 117ksk** [xdy/xdy-pf2e-workbench#1109]
The new changes to BAM aim to hide all actions to a PC that are not available due to required Trained proficiently. As per Archives of Nethys, the Squeeze action requires Trained proficiency in Acrobatics to use. Currently, the Squeeze action is shown to all PCs regardless of proficiency. 

Background on the discussion on required proficiency or not can be found in recent discord post [here](https://discord.com/channels/613968515677814784/738122137943932958/1175650650575605870).

**Comment by xdy** [comment]
Yeah, sounds reasonable. I'll change it to that.
