### ISSUE TITLE
Gather information, decipher writing and make an impression missing (E) in BAM

### ISSUE THREAD

**Issue by essae31** [xdy/xdy-pf2e-workbench#1112]

**Comment by essae31** [comment]
Impersonate also missing the (E)

**Comment by xdy** [comment]
Information about traits is only available on 'new style actions'. Once these actions have been converted in the pf2e system and I've switched over to using them this issue will be fixed. (Not a clue when this will be done, but I noticed Nikolaj just did a couple of actions (climb and swim), so there is progress.
