### ISSUE TITLE
Treat Wounds and Natural Medicine broken again

### ISSUE THREAD

**Issue by thejoester** [xdy/xdy-pf2e-workbench#1124]
Foundry Virtual Tabletop: Version 11 Stable, 11.315
Game System: pf2e, 5.9.5

After the latest PF2E patch (5.9.5) The basic action macro does not show the Treat Wounds (and Treat Disease and Treat Poison) for my Cleric player who has Natural medicine (therefore is not trained in Medicine). 

I found this issue in a past version (https://github.com/xdy/xdy-pf2e-workbench/issues/665) but was fixed. 

I have disabled all modules and also started a new world and it persists.

**Comment by thejoester** [comment]
Also, I did check they have the new Healers Toolkit item

**Comment by xdy** [comment]
BAM uses a macro that is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Treat%20Wounds%20and%20Battle%20Medicine.js
Ping darkim about it on https://discord.com/channels/880968862240239708/880969174661353484 or make an issue on Symon's repo.

**Comment by xdy** [comment]
My bad. This is a workbench issue.
