### ISSUE TITLE
[Feature Request] Add option to exclude loot piles and Item Piles from mystification

### ISSUE THREAD

**Issue by weepingminotaur** [xdy/xdy-pf2e-workbench#1141]
My players tend to use Item Piles to drop items on the map. Would be great if they weren't auto-mystified. Same for Pf2e loot actors.

**Comment by xdy** [comment]
Loot Piles don't mystify for me (the code only mystifies npc actors). Make sure you have set Item Piles to use loot as the actor class type in the System Specific Settings.

**Comment by weepingminotaur** [comment]
OK, I will check Item Piles settings, thanks. But the default Pf2e loot actors are also auto-mystified when they hit the scene. Would be nice if we were able to exclude them from mystification.

**Comment by xdy** [comment]
That doesn't happen to me. (Currently retesting using foundry 11.315 with workbench 5.41.0 as the only active module.)
Try again with no modules other than workbench 5.41.0 or later active.

**Comment by xdy** [comment]
Closing issue as stale.
