### ISSUE TITLE
Treat Wounds / Battle Medicine should be updated to have the Healing trait

### ISSUE THREAD

**Issue by artisauce** [xdy/xdy-pf2e-workbench#1159]
Without the heal/healing trait, the roll made with them is missing the healing button.
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/19614974/55b9ecfe-b66c-4824-b867-51df7378c14b)

**Comment by xdy** [comment]
That macro is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Treat%20Wounds%20and%20Battle%20Medicine.js
Though I'm fairly certain Darkim has fixed that issue, so try upgrading Workbench and checking again.
