### ISSUE TITLE
Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'value') When using Force Barrage Macro

### ISSUE THREAD

**Issue by Badges5790** [xdy/xdy-pf2e-workbench#1163]
Foundry Version: v11.315
PF2e Version: v5.11.5
PF2e Workbench Version: v5.40.2

When using the Force Barrage macro, the macro fails to run if the actor is carrying a wand of Force Barrage. The pop up to select a source for the spell does not appear, and the titled error shows in the console. Based on information from the PF2e Discord Workbench thread, this is caused by the wand charge detection line of code (line 58). Discord user Idle states that item.system.charges is no longer used, in favor of item.system.uses. 

``` JavaScript
for (const s of token.actor.itemTypes.consumable) {
	if (!s.system.traits.value.includes("wand") && !s.system.traits.value.includes("scroll")) { continue; }
	if (s.system.spell?.system?.slug === 'force-barrage') {
		if (s.system.traits.value.includes("wand") && s.system.charges.value > 0) {
			mm.push({ name: `${s.name}`, level: s.system.spell.system.location.heightenedLevel, prepared: false, entryId: s.id, wand: true, scroll: false, spont: false, link: s.link})
		}
		if (s.system.traits.value.includes("scroll")) {
			mm.push({ name: `${s.name}`, level: s.system.spell.system.location.heightenedLevel, prepared: false, entryId: s.id, wand: false, scroll: true, spont: false, link: s.link })
		}
	}
};
```

**Comment by xdy** [comment]
That macro is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Force%20Barrage.js
Though I'm fairly certain the above has been fixed in the most recent version.
