### ISSUE TITLE
Spells not casting privately

### ISSUE THREAD

**Issue by ChrisEurolog** [xdy/xdy-pf2e-workbench#1184]
I am unable to get spells to cast privately in any way despite the appropriate settings being turned on. Please let me know if this is unique to me or a general issue :)

**Comment by xdy** [comment]
Could it be the change from 5.41.0 you're seeing? "Change the 'Cast spell privately' feature so it doesn't cast privately if a party member knows that spell."
Try having an npc cast a spell you know no partymember has.

**Comment by xdy** [comment]
Closing issue as stale.
