### ISSUE TITLE
BAM not working (The customizable one does)

### ISSUE THREAD

**Issue by Araluen124** [xdy/xdy-pf2e-workbench#1194]
When i try to use the BAM, i get that message in the console and the window doesn't open at all. When i try with the customizableBasicActionMacro it works
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/104476123/eeff495f-93b1-4698-9765-f876a9f2642e)

**Comment by JesterOC** [comment]
Stopped working for me when I updated the latest PF2E system update (5.12.0) and nothing else.  Still not working when I updated to the latest version of pf2e-workbench.
work around you provided works
