### ISSUE TITLE
Demoralize not opening roll preview

### ISSUE THREAD

**Issue by ttocs240** [xdy/xdy-pf2e-workbench#1196]
You can't use the shift+click shortcut to bring up the roll dialogue when using the Demoralize macro from the Basic Action Macros when you've disabled the "Preview D20 Rolls" option.

**Comment by xdy** [comment]
That macro is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Demoralize.js
BAM passes the event to the macro, so it should start working if the macro is updated to support bringing up the roll dialogue.
Make an issue on the above gitlab or ask about it in the pf2e discord https://discord.com/invite/pf2e
