### ISSUE TITLE
Feature request : Private spellcasting message only for players

### ISSUE THREAD

**Issue by uniwars** [xdy/xdy-pf2e-workbench#1199]
Hi, could the private spellcasting message 
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/65986545/0fe2b8fa-1d14-486f-b396-d877d3008edb)
be only visible by players via a setting ?
In most cases GM will not use this message so it would only make a duplicate for GM in the chat.

To make the message only visible for players it could be a /w to active players

Thanks

**Comment by reyzor1991** [comment]
```
        let whisper = game.users.filter(u=>u.active).filter(u=>u.id!=ChatMessage.getWhisperRecipients("GM").map((u) => u.id)[0])
        let user = whisper.length > 0 ? whisper[0] : game.userId;

        ChatMessage.create({
            whisper,
            user,
            speaker: ChatMessage.getSpeaker({ token: message.token }),
```

https://github.com/xdy/xdy-pf2e-workbench/blob/1b4248516feb34e13650dabdf32ab4b2a9a0a84c/src/module/feature/qolHandler/index.ts#L244
