### ISSUE TITLE
[Request] Add a number or suffix to demystified creatures

### ISSUE THREAD

**Issue by JerkyGunner** [xdy/xdy-pf2e-workbench#12]
I'd like to be able to demystify any creatures that they know about but when they do it would be ideal if they were differentiated from each other.

So for example a Corrupt Guard would be placed down/demystified as Corrupt Guard 1, Corrupt Guard 2 (or even with random numbers).

**Comment by xdy** [comment]
Implemented in 1.6.0 (as in, if the name of a mystified token ends with a number, that number is kept when the token is demystified)
