### ISSUE TITLE
Missing from settings.

### ISSUE THREAD

**Issue by fireman644** [xdy/xdy-pf2e-workbench#1205]
I updated today and now the module is missing from settings.  Tried downgrading but didn't help. Any ideas? Thanks.

**Comment by websterguy** [comment]
Showing up just fine for me on 5.47.0
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/54455090/bb12ffd9-6b1a-44a2-a9d6-eb603247696e)
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/54455090/656b9ba5-fe87-4f27-8cdd-dd3ff4318d71)

**Comment by xdy** [comment]
If you're on the forge, try again tomorrow, they've been having problems today.
If not, try uninstalling workbench, deleting it's directory in the modules folder and redownloading it.

**Comment by fireman644** [comment]
Thanks bro.  Deleted and downloaded from github and is working again.

Sean G.
