### ISSUE TITLE
[Feature Request] Custom condition in Condition Manager macro for timers

### ISSUE THREAD

**Issue by DiceKnights** [xdy/xdy-pf2e-workbench#1207]
Firstly to whoever created the condition manager, a massive thanks. I use it multiple times a session, and exclusively over the inbuilt one on the tokens. It is so much easier to parse all the various conditions, and add timed conditions. 

I would find it very useful if there was a 'cooldown' condition, that could be added through the "Timed Condition" option that could be used to track abilities on creatures that have a cooldown.  Say a hellhound breath, after it breaths I determine it can be used again after 3 rounds, i can slap a Cooldown 3 condition on that creature as a way of reminding myself when its ready for use again.

**Comment by xdy** [comment]
That macro is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Conditions%20Manager.js
Make an issue there or ping Symon on the discord: https://discord.gg/pf2e
