### ISSUE TITLE
Feature request: a Notification when a player casts a spell privately

### ISSUE THREAD

**Issue by pontusedberg** [xdy/xdy-pf2e-workbench#1217]
sometimes its nice to know for the players to see they have infact rolled a Private Roll feature
Like recall Knowledge, or Spells
A simple chat msg that just states "You attempt to recall some knowledge...." 
send to the player who ask for it, would be great.

**Comment by xdy** [comment]
When I disable '... but don't cast privately if spell known by party' I get this as a player:
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/246024/112e5990-139f-42b8-9209-8f7c02a5e3c8)
so I think this is already handled?

**Comment by xdy** [comment]
Closing issue as it seems to work for me.
