### ISSUE TITLE
Feature Request: 3 diffrent Basic Action macros (Combat, Exploration, Downtime)

### ISSUE THREAD

**Issue by pontusedberg** [xdy/xdy-pf2e-workbench#1218]
The basic action Macro is amazing, but its a bit cluttered
Why not have 3 different buttons for the 3 different types of gameplay
A combat macro, an exploration macro, and a downtime Macro
(we can even keep the old one as legacy content, or for when you need to see everything!)

**Comment by baronfel** [comment]
Looks like the most recent release does this!

![image](https://github.com/xdy/xdy-pf2e-workbench/assets/573979/4b180155-e136-4430-b2e3-7aec88225b97)

**Comment by AvianSnow** [comment]
> Looks like the most recent release does this!
> 
> ![image](https://private-user-images.githubusercontent.com/573979/301649356-4b180155-e136-4430-b2e3-7aec88225b97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjI2MjQsIm5iZiI6MTcwNjgyMjMyNCwicGF0aCI6Ii81NzM5NzkvMzAxNjQ5MzU2LTRiMTgwMTU1LWUxMzYtNDQzMC1iMmUzLTdhZWM4ODIyNWI5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQyMTE4NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZDBhZmU5OTM3NzlmZDE4YTdkYTEzY2Q4Y2FmMzkyYWY4YWY0YWEzOTA2ZTcyZThmODYyMDU4ZDg5YzMzZWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8Fv4cQcrBISY_pqoa-KkK4UZovxxMUIiLB8lGVecQzI)

It does indeed! They added it right after this post! :D

**Comment by xdy** [comment]
Yep, Kali is slaying it with the recent changes. Closing issue as already implemented. :)
