### ISSUE TITLE
Issue: BAM, Actions wich cant be used, is now shown in the new update

### ISSUE THREAD

**Issue by pontusedberg** [xdy/xdy-pf2e-workbench#1228]
I think the new update broke the feature in bam wich would hide Actions wich cant be used if you arent trained in them

![BAM](https://github.com/xdy/xdy-pf2e-workbench/assets/1547673/3329093b-7615-4adb-8fa8-108ce6ce5ef5)

**Comment by AvianSnow** [comment]
im stupid
