### ISSUE TITLE
Recharge Reminder not functioning

### ISSUE THREAD

**Issue by TheTenk** [xdy/xdy-pf2e-workbench#1238]
There is no longer a roll or added effect upon using an ability with a [[/br 1d4 #Recharge Breath Weapon]] type block at the bottom
https://cdn.discordapp.com/attachments/880969174661353484/1204948990785880206/image.png
https://cdn.discordapp.com/attachments/880969174661353484/1204949208377851964/image.png

**Comment by reyzor1991** [comment]
https://github.com/xdy/xdy-pf2e-workbench/blob/58c36a2ef70be15d21306cb002374757cdefb33c/src/module/feature/reminders/index.ts#L18C1-L19C1

Message content doesn't have # in text

`            const formulaMatch = content.match("1d(4|6) #(rounds|Rounds|recharge|Recharge)");
`
Need to change to:
`            const formulaMatch = content.match("1d(4|6) (rounds|Rounds|recharge|Recharge)");
`
