### ISSUE TITLE
Please make it compatible to FVTT 12.x 

### ISSUE THREAD

**Issue by serjevski** [xdy/xdy-pf2e-workbench#1338]
Can't install module on new version of VTT

**Comment by belkasro** [comment]
gonna take time to fix all the code

**Comment by DotBreno** [comment]
I updated to 12.x this week and realized I just don't know how to play without PF2E Workbench anymore, lol. I know it's a lot of work to make it compatible, so I'm not pressing or complaining, just anxious, xD. PF2E Workbench is so good I think it should be part of the PF2E system in Foundry.
