### ISSUE TITLE
Compendium Link Macro needs update.

### ISSUE THREAD

**Issue by bradylantz** [xdy/xdy-pf2e-workbench#1351]
The Compendium Link Macro contains the line 

`temp_macro.permission.default = CONST.DOCUMENT_PERMISSION_LEVELS.OWNER;
`

V12 of foundry API changed this and it now throws an error because it cant find 'OWNER'

The correct line is now: 

`temp_macro.permission.default = CONST.DOCUMENT_OWNERSHIP_LEVELS.OWNER;`

**Comment by xdy** [comment]
This has been updated in the latest version, but, you'll need to reimport all macros. (Or, of course, fix your local copies.)
