### ISSUE TITLE
Seems like all the macros need updating.

### ISSUE THREAD

**Issue by fishrobe** [xdy/xdy-pf2e-workbench#1357]
In V12 none of the macros seem to work anymore (Force Barrage, Recall Knowledge, Treat Wounds / Battle Medicine, Use Wand/Scroll, DC by levels, etc). Clicking on the macros don't do anything. However, if I copy/paste the macro from the XDY_DO_NOT_IMPORT versions and make a "new" macro, those DO still work. I don't know nearly enough about coding to fix however they are linked myself.

**Comment by xdy** [comment]
Unfortunately you need to reimport all macros, after that it should work. (If you are on the latest version.)
