### ISSUE TITLE
[Bug] Foundry V12.327 - Game Paused position and alternate text broken

### ISSUE THREAD

**Issue by tagnullde** [xdy/xdy-pf2e-workbench#1361]
The "Game Paused" location ends up at the top of the screen after activating the module. 
Also the alternate image and text isn't working either.

The image shows the broken position of the icon and that an alternate image and text has been configured but isn't displayed.

![image](https://github.com/xdy/xdy-pf2e-workbench/assets/44159008/4c4b6784-4e61-45b9-86cc-84a74b325b94)

Foundry Virtual Tabletop: Version 12 Stable, 12.327
Game System: pf2e, 6.0.1
Workbench: 6.2.1

**Comment by xdy** [comment]
Fixed now.
