### ISSUE TITLE
Automatically move combatant non-functional

### ISSUE THREAD

**Issue by roguedevjake** [xdy/xdy-pf2e-workbench#138]
The following two features do not seem to be currently working.
- Optional feature to automatically move combatant that goes to 0 hp to just before the current combatant. (See above.)
- Optional feature to automatically move combatant that gets the Dying condition to just before the current combatant. (See above.)

Created a new world with only pf2e workbench enabled to make sure it wasn't a module conflict, 

The manual keybind works fine however. 

Verified with -
Foundry: V9.249
PF2e ruleset: 3.4.4.10487
PF2e Workbench: 2.26.1

**Comment by xdy** [comment]
Hopefully this works again in 2.26.3. I broke a lot of things with the 2.26 release. 'Just cleaning up a bit' is dangerous. :)
