### ISSUE TITLE
Lag, lockups, and stalls after updating to v12.328

### ISSUE THREAD

**Issue by dagit** [xdy/xdy-pf2e-workbench#1381]
I updated to v12 328 today and when click the button to roll damage on the "Damage Roll" pop-up, my browser will stall for several seconds. There's other places where this happens but this is the easiest one for me to reproduce and test with.

I disabled all add-ons except Pf2e Workbench and it happens. I can enable all add-on except Pf2e Workbench and the issue goes away. This is on chromium Version 125.0.6422.60 (Official Build) (64-bit). The version of pf2e workbench is 6.6.4.

On a monk character with wrist wraps and a fire rune, clicking to roll damage for unarmed attack doesn't cause the browser to pause but it does produce this in the js console 
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/384637/d9cde730-22d3-421b-8f59-8c4ef376782b)

Rolling damage for the same character on a different attack does cause the browser to stall out for 5 seconds but doesn't produce anything in the js console. 

At one point I tried to apply damage after an area of effect spell and it took 18 seconds to apply damage to each token. I clicked to apply. Waiting 18 seconds. Clicked to apply. Waited 18 seconds. Etc. It took so long that my operating system wanted to know if I wanted to keep waiting on the browser to respond.

I wish I could give better details on how to reproduce this. The issue isn't specific to the character I roll damage for but the behavior does seem to be different for "Unarmed Attack" vs any other attack I roll. With "Unarmed Attack" there is no delay but there is an exception in the js log. With all other attacks I've tried there is a delay but no exception.

My players were not seeing this behavior but as GM it extremely disruptive as any time my players rolled damage it would make my browser lockup for 5+ seconds.

**Comment by dagit** [comment]
Apparently this was caused by having an excessive number of messages in the chat history.

**Comment by xdy** [comment]
I always clean out the chat log after eftery session (and occasionally during it) so I rarely think of problems that can cause. I'll see if I can improve things a bit at least.

**Comment by xdy** [comment]
And, fix the actual bug that I just noticed. :)
