### ISSUE TITLE
[Bug] Persistent Damage automatic application and Recovery Roll automation are broken

### ISSUE THREAD

**Issue by shauneb** [xdy/xdy-pf2e-workbench#1389]
The recent change: "fix: Made Breath Weapon reminder a bit more robust" added the following code to hooks.ts 
if (!game.messages.contents.slice(-Math.min(1, game.messages.size)).filter((x) => x._id === message.id)) {

This seems to always evaluate false, so the persistent damage and recovery automation handlers are never being called.

This is my first contribution on this project, and I'm not a javascript expert, so I'm not creating a PR in case I missed something obvious.

**Comment by xdy** [comment]
Should be fixed in the latest version.
