### ISSUE TITLE
Mystification is renaming tokens to an original state

### ISSUE THREAD

**Issue by KLSteinwand** [xdy/xdy-pf2e-workbench#14]
So the gist is that if a token had been laid down previously with another sequencing module (Token Mold for this instance), when attempting to mystify the token, it will change the name back to it's original name when placed, and then will allow the token to be mystified. Replication steps are per follows:

1. With the Token Mold module active and Workbench inactive, place a few tokens for reference with Token Mold's sequencing options enabled. Once token(s) are placed with a sequenced number, close the Foundry application, and then relaunch.
2. Following the same procedure as just performed, place more token(s) down and change the number that has been provided to the token through the token editor to a different number as they will initially follow a new order of sequencing.
3. Once a second set of tokens has been placed, activate the Workbench module (Token Mold can remain active or be in active, neither state affects this) and disable the options for numbers to be applied to tokens.
4. Select any token from the second set that was placed and the sequenced number changed, attempt to mystify the token. It will first change the current token name to it's original name, and then will mystify on a second attempt. When un-mystifying the token, the name will reappear as the original name that was initially given before any kind of changes were made.

There are no errors or warnings that appear in the console when this process is performed, and showing it in action would require the use of screen capture to record video of the instances occurring.

**Comment by xdy** [comment]
Try to figure out how to handle names like 'Goblin (5)' (as made by Token Mold).

**Comment by xdy** [comment]
I couldn't come up with a decent fix for this, so, I settled for documenting it in the setting hint:
hint: "Turns on adding a random number when mystifying npcs. Note that if the token or actor already has a number as a suffix this will not work well."
