### ISSUE TITLE
Depreciation Messages in Workbench Settings

### ISSUE THREAD

**Issue by ottyn** [xdy/xdy-pf2e-workbench#1447]
When opening any of the sub-menu options in Workbench's Settings, you get the following Warning in console.
Foundry 12.331
PF2e 6.2.3
Workbench 6.8.0

![image](https://github.com/user-attachments/assets/635c249d-4a85-4f63-a66b-05800a3a3cf0)

**Comment by xyzzy42** [comment]
Fixed in #1474
