### ISSUE TITLE
[BUG] BAM macro Treat Wounds Additional Healing Calculation seems wrong for Proficiency

### ISSUE THREAD

**Issue by Neakas** [xdy/xdy-pf2e-workbench#1484]
So i think i found a Bug in the Treat Wounds Macro. One of my Players has the Medic Dedication.

The Treat Wounds Action states:

"The Medicine check DC is usually 15, though the GM might adjust it based on the circumstances, such as treating a patient outside in a storm, or treating magically cursed wounds. If you're an expert in Medicine, you can instead attempt a DC 20 check to increase the Hit Points regained by 10; if you're a master of Medicine, you can instead attempt a DC 30 check to increase the Hit Points regained by 30; and if you're legendary, you can instead attempt a DC 40 check to increase the Hit Points regained by 50"

The Medic Dedication states:
"You become an expert in Medicine. When you succeed with Battle Medicine or Treat Wounds, the target gains a circumstance bonus to the number of Hit Points they regain equal to 5 HP at DC 20, 10 HP at DC 30, or 15 HP at DC 40."

so if we roll Treat Wounds (as an Expert in Medicine with the Medic Dedication) against the DC20 we SHOULD get +15 Bonus Healing from the Treat Wounds.

Now funny enough, the Macro UI does show the Correct Number 

![grafik](https://github.com/user-attachments/assets/cfd70f65-be71-42a6-bfaf-bd101e53e7a9)

since the Macro Code does check for the Medic Dedication

![grafik](https://github.com/user-attachments/assets/f600af3a-85a1-4175-90a7-75a76e3a79b5)
"do +15 else +10" looks fine.

BUT the Roll then is only +5
![grafik](https://github.com/user-attachments/assets/bf3cc9e2-c362-403a-bf45-e0fb2b22ee15)

the bug should be in the Macro here:

![grafik](https://github.com/user-attachments/assets/bc9a8325-b768-42bc-a402-9f329f4adcb7)

the Bonus Damage is only ever 0, no matter what the Proficiency was.

**Comment by xdy** [comment]
This should be fixed. If not, open another issue.
