### ISSUE TITLE
Spellstrike macro issue on critical hits

### ISSUE THREAD

**Issue by JJellie** [xdy/xdy-pf2e-workbench#1491]
Since most of the spells have been remastered and the spellstrike macro handles all spell crits manually, the spells do not crit if the spellstrike crits. This is probably an issue with the remastered spells having different slugs.

**Comment by xyzzy42** [comment]
Can you name any specific spells?

**Comment by JJellie** [comment]
From the top of my head. Ray of frost and Gouging claw, I should be able to give a more thorough report on Monday

**Comment by xyzzy42** [comment]
Gouging claw, remaster, doesn't have a special effect or damage on crit.  It just does double damage, so you click the double button when applying the damage.  It's the same as the way most attack spells work.

Ray of Frost is missing the crit effect (-10' speed).  That hasn't been there for as long as I remember.  None of the extra effects on crit show up in the damage card.

The remastered Ray of Front is Frostbite and it's a saving throw spell now.  The strike doesn't determine outcome for those.  There's is still a save and critical failure on the save might cause an additional effect.

**Comment by JJellie** [comment]
You are indeed right. I misunderstood it myself then, this issue can be closed as resolved

**Comment by xyzzy42** [comment]
Ray of Frost could add the effect to the damage card.  But it's not trivial to alter the damage roll from spell, so it probably won't be added just for a single legacy spell.

The way all the saving throw spells are handled could be better I think.  It does the damage roll for the spell, but not the main spell cast card.  There's a number of things that don't work well with this:
1. There's no save button in chat.  The spell is linked from the strike attack roll card, but that link doesn't have a save button either.
2. There's no place a template button.  AoE spells still affect their AoE.
3. It doesn't interact with Toolbelt's Target Helper.  No save button per target.  No damage to target(s) button(s).
4. If there's an effect, it's necessary to open the spell up from the strike attack card to get the effect link.  It would be more convenient if it was already in chat.
5. If the target critically succeeds at the save, they still see the damage roll.
