### ISSUE TITLE
Treat Wounds macro DCs don't adjust to Proficiency Without Level

### ISSUE THREAD

**Issue by Marcloure** [xdy/xdy-pf2e-workbench#1514]
The DCs of the _Treat Wounds and Battle Medicine_ macro are hardcoded to 15, 20, 30, 40, so they don't automatically adjust when Proficiency Without Level is enabled in the system settings. They should scale to 15, 20, 25, 30 as per the table in the PWL variant rule.

**Comment by xdy** [comment]
Should be fixed once https://gitlab.com/symonsch/my-foundryvtt-macros/-/merge_requests/141 is accepted.
