### ISSUE TITLE
Treat Wounds/Battle Medicine + Chirurgeon Research Field

### ISSUE THREAD

**Issue by 7H3LaughingMan** [xdy/xdy-pf2e-workbench#1541]
For some reason the Treat Wounds/Battle Medicine macro still seems to require that you be trained with Medicine even though you don't need to be with the Chirurgeon Research Field. When attempting to use the macro while untrained in Medicine it complains that you can only target 0.5 targets.

**Comment by xdy** [comment]
Should be fixed once this PR is in: https://gitlab.com/symonsch/my-foundryvtt-macros/-/merge_requests/141
Turns out I *was* likely to keep fixing the macro. :)
