### ISSUE TITLE
Treat Wounds/Battle Medicine + Right-hand Blood

### ISSUE THREAD

**Issue by 7H3LaughingMan** [xdy/xdy-pf2e-workbench#1542]
Right-hand Blood is an ancestry feat that can be taken by Kholos, it allows you to damage yourself for 2d8 damage and lets you use Treat Wounds without needing a healer's toolkit and provides a +1 item bonus to your check. Would be nice if there was an option to say that you are using this feat when you don't have a healer's toolkit.

**Comment by xdy** [comment]
Should be done once https://gitlab.com/symonsch/my-foundryvtt-macros/-/merge_requests/142 has been merged.
