### ISSUE TITLE
Treat Wounds/Battle Medicine Macro not working

### ISSUE THREAD

**Issue by GM-Swan** [xdy/xdy-pf2e-workbench#1545]
The latest update of Pathfinder Second Edition seems to have broken the Treat Wounds/Battle Medicine macro provided by PF2e Workbench. When targeting a character, clicking the macro does nothing now. It used to bring up the dialog window with options.

Foundry v12.331
PF2e v6.7.2
PF2e Workbench v6.12.4

**Comment by Marcloure** [comment]
I'm having this issue as well. This is the error I see:
![image](https://github.com/user-attachments/assets/76bf96e4-5fa1-426c-8fbb-4aa9f9eed055)

**Comment by gralamin** [comment]
Looks like the source repo has been fixed here:
https://gitlab.com/symonsch/my-foundryvtt-macros/-/merge_requests/139

I think someone just needs to pull it into workbench and distribute the new version? Not sure how this maintained.

**Comment by xdy** [comment]
The fix has now been released.
