### ISSUE TITLE
Request: Clean up settings.

### ISSUE THREAD

**Issue by Lexaj-dev** [xdy/xdy-pf2e-workbench#163]
I like that this module ist so incredible customizable, but it would be nice if its setting entry was a little more compact.

I saw in other modules that it is possible to have buttons in the settings to open separate windows, and I'd like to see the NPC-Mystifier customization go into it's own window.

**Comment by xdy** [comment]
I agree, it's getting to the point where even now that I default to hiding options it's getting way too big.
Won't happen immediately though. Need to figure out how to do it first. :)

**Comment by CarlosFdez** [comment]
I can help you with this if you want. It'll be more or less how we handle it in pf2e's system for the buttons. I could do it for mystification settings and you could copy paste for other things afterwards?

**Comment by CarlosFdez** [comment]
![image](https://user-images.githubusercontent.com/1286721/178128850-b39c3dfa-3663-475c-9f8d-b81208dd170a.png)

Can make a PR if this is what you're looking for

**Comment by xdy** [comment]
Looks great! I'll take a look at your PR later tonight, and hopefully be able to apply that to the rest of the settings mess next week. Vacation starts on tuesday, so hopefully more time for happy hacking. :)

**Comment by xdy** [comment]
Later tonight just happened, so your PR is in the upcoming release, thank you!

**Comment by xdy** [comment]
With the latest cleanup I think this issue can be closed. Not perfect, but good enough.
