### ISSUE TITLE
mystify "null" prefix - request

### ISSUE THREAD

**Issue by MarkPearce** [xdy/xdy-pf2e-workbench#165]
allow users to completely remove the prefix word. (eg Unknown) 
If I leave it blank or put a space, "Null" is prepended to mystified names.
my workaround is to use "."

so the best I can get is have ". undead" ". aberration" etc...

<blockquote class="imgur-embed-pub" lang="en" data-id="a/nmKmj5h"  ><a href="//imgur.com/a/nmKmj5h">null prefix</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by xdy** [comment]
Hmm. That does not seem to happen for me in either firefox or chrome. Is some other module interfering? Does it work if you make a new test world?

https://user-images.githubusercontent.com/246024/160243655-8e033a85-aa59-40c4-b1b8-c74b4b6e4790.mp4

:

**Comment by MarkPearce** [comment]
Ah must be on my game world, not happing in a fresh test world. :(

i'll try to isolate conflict
