### ISSUE TITLE
Request: Two Features for Critical Sounds

### ISSUE THREAD

**Issue by Armandeus66** [xdy/xdy-pf2e-workbench#207]
Thank you for all your work on this great module!

Thanks for adding the ability to use tables of sound file paths to reference sounds for critical success/failure strike rolls!

Why I am asking for this:
In addition to melee hitting sounds, I like to use meme sounds (applause, famous sayings, etc.) to congratulate players on critical success, and make them laugh on critical failure.
I use Maestro and Dice So Nice for 1 or 20 die results, but they do not support the PF2E +/-10 critical system. Maestro is good because it calls sounds from a playlist, and Dice So Nice can call macros. Another such module, Confetti, only plays one preset sound and only on a 1 or 20. The existence of these modules shows using congratulatory or funny sounds with critical rolls is something some users like.
I have requested PF2E critical detection (it is on the chat cards, so it's doable, I think) from the authors of Maestro and DSN a while ago, but I think they are more interested in D&D5E than supporting Pathfinder.

I would like to request two alterations to Workbench, if that would be all right.

1. Please extend detection of critical success/failure to non-strike DC checks as well as the current strike rolls, for the sake of playing sounds in the same way. One way to do it would be to make their settings separate from the strikes, so you could use a separate set of sounds for strike and non-strike rolls. Maybe you wouldn't need animation for the non-strike crits.
2. Please allow the user to select a Foundry playlist (instead of having to make a table of file paths) to use the random sound feature. Playlists are built into Foundry, and everyone can use them easily. Tables of multiple file paths take time to copy and paste, or require a macro to create automatically, which adds another level of difficulty to using this feature.

(I am not asking that the current ability to specify only one sound for critical strikes be changed. That is great as it is and I'm sure many people are happy with it.)

Thank you!!

**Comment by Armandeus66** [comment]
Thanks for doing item 2 on my list in the latest release!

I'm looking forward to item 1 someday, if possible. Thanks again!

**Comment by xdy** [comment]
As support for sounds and animation on hits and misses is deprecated and will soon be removed (replaced by better functionality in https://github.com/MrVauxs/pf2e-jb2a-macros) I'm closing this issue.
