### ISSUE TITLE
hero point reminder timer

### ISSUE THREAD

**Issue by belkasro** [xdy/xdy-pf2e-workbench#218]
not sure if this a known issue or not. i sue forge for foundry and wonder if you can add a manual restart timer for the hero point reminder. works well on normal foundry but on forge the worlds dont really stop..

**Comment by xdy** [comment]
Yeah, there were definitely some problems there, but I think I've fixed this one (at least, it works for me on the Forge).
I have the 'automatically start hero point handler' setting enabled, when I go to a world I get a message like "Hero Point Handler returns in 60 minutes (19:15).", which is what I'd expect.
I'll close the issue, do reopen if if you still have a problem.

**Comment by belkasro** [comment]
I got it working since you updated it. Thanks for the update though.

**Comment by belkasro** [comment]
Is there a possible way to make a better loot Gen for 2e. Magic wands
andnscrolls broke not sure you are the same guy that does the same thing.

**Comment by xdy** [comment]
No, the Toolbox is a separate (now delisted) module.  I'm unlikely to pick up that feature, the nearest I know of is the macro 'Loot Generator' (not made by me, I just provide that macro with module with the makers permission, the original can be found at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Loot%20Generator.js)

**Comment by belkasro** [comment]
Cool, thanks!

You got a patreon or way to support you. Love the work you are doing. Hope
you or someone makes a decent encounter Gen for pathfinder 2 in the near
future.
