### ISSUE TITLE
Suggestion: Dirge of Doom effect improvement

### ISSUE THREAD

**Issue by roguedevjake** [xdy/xdy-pf2e-workbench#220]
I recommend using a grantitem rule element to give the frightened condition via the compendium uuid. Allows for better ruleset integration and greater clarity for players/gms that may have.

(I have been working through the CRB spells and automating as many as I can, makes synesthesia a lot nicer to apply.)

**Comment by xdy** [comment]
Oh, right. I only intended that as an example of the flag you could set, but sure, making it into a complete Dirge of Doom effect makes sense however (well, more complete, I still won't handle the aura).
I'll include that in the next release.
