### ISSUE TITLE
[Issue/FeatureReq] Critical and Miss Animations consistently off the mark 

### ISSUE THREAD

**Issue by MrVauxs** [xdy/xdy-pf2e-workbench#236]
The Critical Hit/Miss animations are constantly appearing in the wrong positions at the screen, sometimes following when the actual strike animation ends, but often just going anywhere.

It would be beneficial to simply have the animations play on the attackers or targets token, or as another option, where the strike animation ends.

**Comment by MrVauxs** [comment]
Foundry 9.269
PF2e 3.9.0
pf2e-workbench 2.50.1

**Comment by xdy** [comment]
That's intentional (and a feature of Automated Animations). I set playOnMiss to true on misses and critical misses, which means that the animation will appear at a random location near the missed target token.
But, I'll expose a setting to turn that off in the next release.

**Comment by MrVauxs** [comment]
I will mention that JB2A just added a Critical Miss/Fail animation, which you can use in your presets now.
