### ISSUE TITLE
Undetected goes nuts if Loot sheet is marked Hidden when empty

### ISSUE THREAD

**Issue by Geodragon9** [xdy/xdy-pf2e-workbench#237]
As per the subject line.  Dropping an empty loot chest unto the map, it immediately goes hidden, and then undetected just spastically pops over the token many times.  And I can't unhide it nor add anything to the chest.. I had to delete it, and then turn off the hidden when empty on the loot sheet.

**Comment by xdy** [comment]
I wasn't able to reproduce this, but Loot actors shouldn't have the Undetected state anyway so I'll simply exclude them.
