### ISSUE TITLE
Make animations appear off-target setting does not work

### ISSUE THREAD

**Issue by MrVauxs** [xdy/xdy-pf2e-workbench#245]
As the title implies, despite turning the setting off, miss and even critical hit animations consistently appear off-target.
![image](https://user-images.githubusercontent.com/32039708/167254635-41a0312e-76da-49d4-9ee9-20b5b41f8b42.png)

**Comment by MrVauxs** [comment]
![chrome_im3Sb6jt3L](https://user-images.githubusercontent.com/32039708/167254679-c01ba714-a2f1-4171-b5ef-717838d42be1.gif)
![chrome_FBh92Bd89I](https://user-images.githubusercontent.com/32039708/167254692-0522d203-06b3-4c32-baad-96ba5f17bec7.gif)

![image](https://user-images.githubusercontent.com/32039708/167254708-eac629f1-124c-49ac-823a-a6f315cdeda3.png)

**Comment by xdy** [comment]
That is strange. As you can see it works for me:

https://user-images.githubusercontent.com/246024/167290782-4afc9d7c-65c6-46d5-99e5-d5a1369bdd34.mp4

![image](https://user-images.githubusercontent.com/246024/167290798-80b61e14-821c-4ae6-80df-efe025877f58.png)

Could you try with only the modules I used? (I.e. The Workbhench, AA and it's dependencies.)

**Comment by xdy** [comment]
I also tried with the current release (the above was on a developer build), which also worked.

**Comment by MrVauxs** [comment]
> That is strange. As you can see it works for me:
> 
>  Video.mp4 
> ![image](https://user-images.githubusercontent.com/246024/167290798-80b61e14-821c-4ae6-80df-efe025877f58.png)
> 
> Could you try with only the modules I used? (I.e. The Workbhench, AA and it's dependencies.)

Still appears with the modules you posted. Only difference is that I have an up to date JB2A collection.
![image](https://user-images.githubusercontent.com/32039708/167299776-6ab6ee08-5838-4182-a3fa-49bfbc6dd3c1.png)

**Comment by xdy** [comment]
I updated to the latest JB2A but that made no difference.
For me it works in both Chrome and Firefox, as player and as gm.
Does it work if you make a new test world?

**Comment by MrVauxs** [comment]
It does.

I can give access to the world, if you want. Would rather do it over on Discord though. MrVauxs#8622

**Comment by MrVauxs** [comment]
The issue is with play Animations on Hits and Misses setting in Automated Animations. For some reason the animations from the workbench and AA are coupled together.

![image](https://user-images.githubusercontent.com/32039708/167627245-ab1dea25-98cc-4c5d-ac7f-82ff7836784a.png)

**Comment by MrVauxs** [comment]
Any progress on this?

**Comment by xdy** [comment]
As support for sounds and animation on hits and misses is deprecated and will soon be removed (replaced by better functionality in https://github.com/MrVauxs/pf2e-jb2a-macros) I'm closing this issue.
