### ISSUE TITLE
Suggestion: Turn Workbench Flat Check Notes to Society Boons

### ISSUE THREAD

**Issue by MrVauxs** [xdy/xdy-pf2e-workbench#247]
It's way more out of the way than Deity Boons which are located in the effects tab.

**Comment by xdy** [comment]
Not if you play PFS campaigns. :)
(I don't, but it seems a lot of people do.)

**Comment by xdy** [comment]
I made them into Equipment as that means they can be added to npcs as well.
But, I instead recommend the module https://github.com/jessev14/pf2-flat-check/ as that does a better job with flat checks.
