### ISSUE TITLE
"Sneak attack" animation support. 

### ISSUE THREAD

**Issue by dac0n** [xdy/xdy-pf2e-workbench#251]
Make attacks with a class ` <span` class="damage-tag damage-tag-modifier">Sneak `Attack ` 
automatically play "Sneak attack" animation, either from JB2A or custom. (like a criticall roll / miss animations)

**Comment by xdy** [comment]
As support for sounds and animation on hits and misses is deprecated and will soon be removed (replaced by better functionality in https://github.com/MrVauxs/pf2e-jb2a-macros) I'm closing this issue.
