### ISSUE TITLE
Item quantities and bulk issue

### ISSUE THREAD

**Issue by gideonpepys** [xdy/xdy-pf2e-workbench#258]
Having an issue with Quantity and Bulk of items in character sheet and other equipment lists.  When I use the + or - buttons, [object Object] appears under Quantity and NaN;NaNL appears under Bulk.  I recently installed both PF2e Dorako UI and PF2e Workbench (and checked the box allowing shift and Ctrl to add +5 and +10 items).  I have since uninstalled both, but the problem persists. Thought I would contact you here, as it seems like this function is the most likely culprit. Thanks in advance for any help you are able to offer.

**Comment by xdy** [comment]
Resolved in discord (https://discord.com/channels/880968862240239708/880975811279204402/974642782373290025), closing issue.
