### ISSUE TITLE
Recall Knowledge suggestion

### ISSUE THREAD

**Issue by roguedevjake** [xdy/xdy-pf2e-workbench#272]
A player RAW does not know what skill was rolled for a recall knowledge check (by default, a gm can always reveal ofc).

The player chooses to recall knowledge, the gm rolls the relevant skill as a secret roll and reveals the result. To accommodate for this the following could be implemented

- To Recall Knowledge <span data-visibility="gm">(with [SKILL])</span> about [NPC], roll: 

- Add **name:Recall Knowledge** to the @Check inline roll prompts to obfuscate which check is being rolled (this way the GM can always tell the player if necessary but if they simply click to roll it will be less obvious.

**Comment by xdy** [comment]
I've tried to implement this, but the system ignores the name I set. As a player it still shows the skill name no matter what I as a GM change in 'Limit Metagame Information'. So, I'm afraid I can't do this issue.

E.g. enter this in a chat box and see what happens as a player. Or, well, doesn't happen.
```@Check[type:occultism|dc:32|name:This name is not shown]```

**Comment by roguedevjake** [comment]
@xdy 

> I've tried to implement this, but the system ignores the name I set. As a player it still shows the skill name no matter what I as a GM change in 'Limit Metagame Information'. So, I'm afraid I can't do this issue.
> 
> E.g. enter this in a chat box and see what happens as a player. Or, well, doesn't happen. `@Check[type:occultism|dc:32|name:This name is not shown]`

Ah sorry that is my mistake You actually want something like the following.

`@Check[type:occultism|dc:32]{This name is shown instead of the skill}`
