### ISSUE TITLE
Expand Damage Types by Default, and a compact view for them.

### ISSUE THREAD

**Issue by apoapostolov** [xdy/xdy-pf2e-workbench#273]
Damage rolled by damage type is always hidden, making it very hard for new players to recognize how to apply their resistances. Please consider adding an option that expands these damage types by default and makes them more compact, just one line. 

![image](https://user-images.githubusercontent.com/4083812/172025870-f952095a-5f96-466c-a1fc-4ae50492be1d.png)

In a perfection solution, the damage type is always visible and very compact way per damage type would be like this:

![image](https://user-images.githubusercontent.com/4083812/172027266-70734d91-5596-43bd-8335-0390225e1c1c.png)

**Comment by roguedevjake** [comment]
Agreed.

Although I really wish there was at least some handling of immunity/resistance in the core system it and duration tracking are probably the two biggest problems the PF2e foundry ruleset faces atm imo.

**Comment by roguedevjake** [comment]
For the OP, if you get this and want compacted damage results using the custom CSS module you can get by using the following dirty CSS rules. It will hide the dice results but I figure they aren't actually that important and most people use dice so nice anyway 99% of the time). The h3 element style may cause issues but is just there as a dirty margin remove. 

There are better solutions, but this is a nice and lazy one for now. 

```
.dice-tooltip .dice-rolls {
    height: 0px;
    margin-top: 0px;
    margin-bottom: 0px;
}
h3 {
    margin: 0 0 0;
}
```

**Comment by xdy** [comment]
Oh, right. Forgot about the compact view. Ah well, I suck at css so probably couldn't have made it work anyway. :)

**Comment by xdy** [comment]
@roguedevjake are you ok with me using your css if I revisit this later?

**Comment by roguedevjake** [comment]
@xdy 
No problems, I don't think it will have much of an impact elsewhere... But I can't promise it (just wanted to give the OP a quick option)

Just remember to note in the option that it hides the dice values, as some folks might get confused by that.

**Comment by apoapostolov** [comment]
Thank you very much, and I am well versed with Custom CSS so applying the compact fix is a no brainer. Looks very nice now, at least the players will always see the damage types nicely presented with colors and everything.

**Comment by apoapostolov** [comment]
Is there an easy way with Custom CSS to remove the damage total panel?

![image](https://user-images.githubusercontent.com/4083812/172067769-ef2ca46c-00ea-40bd-bd4d-6613f7ec59c0.png)

**Comment by apoapostolov** [comment]
Is there a way to remove the dice total but only for the Damage rolls? 

![image](https://user-images.githubusercontent.com/4083812/172067831-1c0d07fa-8d6a-4a5e-8879-7aad419dd9af.png)

**Comment by apoapostolov** [comment]
Sorry if I am asking too much out of this, but is it possible for workbench to add a CSS class to damage dice only, so I can use Custom CSS to remove the dice-total only on damage rolls?

**Comment by xdy** [comment]
Yeah, that should be possible. I'm out of time for this weekend, but I'll reopen this issue so I remember it later.

**Comment by xdy** [comment]
I think this is fairly well covered by the upcoming IWR automation in the system, so closing this issue.
