### ISSUE TITLE
Recall Knowledge posts come broken 

### ISSUE THREAD

**Issue by apoapostolov** [xdy/xdy-pf2e-workbench#275]
When I post a Recall Knowledge post from a monster, it comes out with broken links. 

![image](https://user-images.githubusercontent.com/4083812/172174061-4b27e932-6813-4a53-af85-936d919bdd29.png)

**Comment by xdy** [comment]
Hmm. It works for me:
![image](https://user-images.githubusercontent.com/246024/172796498-4b4dca41-2153-4918-b02e-6145a48e9954.png)
Some module that interferes perhaps?

**Comment by apoapostolov** [comment]
I will check and report.

**Comment by apoapostolov** [comment]
OK I found the problematic mod. It is one of the mods that shouldn't be mentioned, for another system, that I used for its UI improvement features.
