### ISSUE TITLE
Support for Flat Checks against Concealed and Hidden conditions 

### ISSUE THREAD

**Issue by apoapostolov** [xdy/xdy-pf2e-workbench#282]
When making an attack roll with a selected target that has the Concealed or the Hidden condition (for now, until PF2E implements vision modes support) triggers a Flat Check roll using the DC 5 and 11 of the core rules.

**Comment by xdy** [comment]
A (somewhat hacky) way of doing that is already part of the module, add the item 'Workbench Flat Check Notes' to the characters or npcs that you want this for. (It contains the various rules elements needed to automate this for that character.)

**Comment by apoapostolov** [comment]
This is good for players, but it won't be usable for monsters I am afraid. And I am trying to get reminded when players attack monsters who are Hidden or Concealed.

**Comment by xdy** [comment]
This is now part of the PF2e Flat Checks module.
As you know. :)
