### ISSUE TITLE
IWR Improvement: Post alignment of target if damage roll includes alignment damage

### ISSUE THREAD

**Issue by apoapostolov** [xdy/xdy-pf2e-workbench#303]
If the damage type word is lawful, good, chaotic, evil, neutral; trigger reminder that will say something like: "{Creature} ({Alignment Abbreviation, i.e. CN}) is unaffected by {damage's alignment} damage."

Example: Hell Hound does 1d6 evil damage. The target is CN and will be unaffected. The reminder says "Leana (CN) is unaffected by **evil** damage."

**Comment by xdy** [comment]
Closing as I will remove this feature in the next release as full IWR support is soon part of the system.
