### ISSUE TITLE
PF2e tool box feature

### ISSUE THREAD

**Issue by belkasro** [xdy/xdy-pf2e-workbench#312]
any way to steal the PF2e tool box Loot sheet generator or make a loot sheet that gens up treasure on the fly?

https://raw.githubusercontent.com/Djphoenix719/FVTT-PF2EToolbox/master/.github/treasure-generator-v1.png

**Comment by LebombJames** [comment]
The Loot Generator macro may be a suitable replacement for you 🙂

**Comment by xdy** [comment]
I doubt I'll take over the Loot generator, the macro is good enough imho. Closing this issue.
