### ISSUE TITLE
Feature Request: Mid-click mouse button to edit effect in the Effect Panel

### ISSUE THREAD

**Issue by apoapostolov** [xdy/xdy-pf2e-workbench#320]
This would help to edit Effects and add descriptions, modify a rule element or edit duration, without having to open the character sheet, find the right tab, and edit the effect from there.

**Comment by xdy** [comment]
Extempore Effects just added this, so closing this issue: https://github.com/itamarcu/pf2e-extempore-effects/releases/tag/1.2.0

**Comment by apoapostolov** [comment]
Thanks, I am in contact with Extempore dev and he is doing great job implementing effect-related improvements.
