### ISSUE TITLE
[Bug] NPC Scaler not updating certain stats

### ISSUE THREAD

**Issue by JerkyGunner** [xdy/xdy-pf2e-workbench#324]
As seen in the images below, the NPC scaler doesn't appear to be updating AC, initiative, Perception, and saves. (which it definitely used to do before)

It's also not updating DCs found inside abilities but I'm not sure if this is something it used to do before.

![image](https://user-images.githubusercontent.com/11801379/177708578-ad29fe21-240c-4f0f-bb07-6a0672fc9f89.png)

![image](https://user-images.githubusercontent.com/11801379/177708158-b90c885a-a178-49ae-9cd8-b8469abffc9d.png)

**Comment by xdy** [comment]
Fixed in 3.20.0
