### ISSUE TITLE
Feature Request: Port Quick Roller from PF2EToolbox

### ISSUE THREAD

**Issue by sean-clayton** [xdy/xdy-pf2e-workbench#326]
The Quick Roller lets you easily roll for a creature or hazard without having to create a dedicated sheet for it. It's essentially multiple tables with levels and their associated modifiers for various things such as attacks, damage, skills, etc from the GMG. Clicking on a cell in this table lets you roll the associated dice with its associated modifier, letting you roll for everything a creature or hazard needs at any level without building the creature or hazard. Really nice for sandbox games where you have to immediately roll for something you didn't think would happen and still maintain the nice balance and tightness of 2e.

Here is the core of the aforementioned code:

https://github.com/Djphoenix719/FVTT-PF2EToolbox/tree/master/src/module/roll-app

**Comment by sean-clayton** [comment]
@xdy If this is something you'd be okay with in this module, I could probably port it over myself and create a PR.

**Comment by xdy** [comment]
Sure, go ahead! I'd probably get around to it *eventually*, but that might be months. :)
DJ's code is in good shape so shouldn't be very hard. Look at how I did cr-scaler and creature-builder and do it like that. I guess the setting to enable it should end up in the QoL settings menu.

**Comment by xdy** [comment]
Oh, one thing that might be worth noting. Don't port over RollAppData.ts, instead use https://github.com/xdy/xdy-pf2e-workbench/blob/main/src/module/feature/NPCScaleData.ts, I don't see the point to maintaining several sets of that data.
