### ISSUE TITLE
Recall Knowledge button scramble game

### ISSUE THREAD

**Issue by Volkmar77** [xdy/xdy-pf2e-workbench#329]
If a player has observer permissions or higher on an NPC token, opens the NPC sheet and click on the "recall knowledge" button, it reloads the game for that player and the whole chat box and menus is removed and the rest of the screen is completely jumbled, making the game impossible to play.
A reload does not fix the problem, only a server stop and start will do.
Attached screenshot shows the screen of a player after pressing the button.
My assumption is that the button moved the chat window somehow and the rest of the screen tried to adapt? 
Anyhow, while I understand this is not the intended use of the feature and when the GM clicks the button, it works as intended, it still can break the game if a player accidentally click that button on an NPC they have access to (allies or friends etc.)
![recall](https://user-images.githubusercontent.com/94173379/178435034-2d3842fe-9e91-4fa8-9821-d3aaa09f6cce.jpg)

**Comment by xdy** [comment]
Oh, right, this should only be run by the GM. Thanks, will fix in next release.
