### ISSUE TITLE
Add setting to obscure creature names in damage card et all

### ISSUE THREAD

**Issue by Burrowfield** [xdy/xdy-pf2e-workbench#334]
PF2e core has the ability to hide creature names in - most - cards. Damage cards are a notable exception. Would it be possible for you to 'private' bracket creature names in the damage card and other such instances, or simply obfuscate them with a global setting? 

![image](https://user-images.githubusercontent.com/1859214/178470088-33179df3-7f21-4bba-b388-bd2f94a84248.png)

Another great example of it being spoilerific is the recall knowledge prompt:

![image](https://user-images.githubusercontent.com/1859214/178470331-9f25424e-be0c-4a12-a9f7-85308ceeb185.png)

**Comment by xdy** [comment]
I use, and recommend, the Workbench's Token Mystification feature to handle this problem (i.e. the token name is something random, in my case also with the base creature trait and a number. E.g. Drustan might become something like 'Angry Humanoid 23') so I've never used the system's hide token name settings.
As for Recall Knowledge, it has a separate flag to hide the name 'Hide NPC name on Recall Knowledge message'.

For the other places I think it'd be better to ask for system support.

**Comment by Burrowfield** [comment]
I think you're right, I just used the mystification and that fixed the issue. I'll rely on that!
