### ISSUE TITLE
Feature Request : Add option to hide the name of the creature in the spell recall knowledge check when using CTRL to secretly cast a spell

### ISSUE THREAD

**Issue by Vertigo522** [xdy/xdy-pf2e-workbench#343]
as per the title, add an option to hide the name of the spellcaster on the recall knowledge chat message.

**Comment by xdy** [comment]
Sort of handled in version 3.37.0 (If the pf2e system's metagame setting 'Tokens determine NPC name visibility' is set, casting a private spell *always* hides the caster name.)
