### ISSUE TITLE
[Suggestion] No Match Text with Random Numbers

### ISSUE THREAD

**Issue by Vaizt** [xdy/xdy-pf2e-workbench#345]
In NPC Mystification Settings, enabling 'Add a random number to name' will override 'No match text' because the random numbers count as a match. Is there any way we can have this excluded? I like to have enemies named 'Unknown' and being able to tack on the random numbers without editing them in myself would be pretty nice.

**Comment by xdy** [comment]
The reason for the 'No match' is that setting a token's name to "" isn't handled well by foundry/the pf2e system. So, checking it is done last in case some wacky combination of settings accidentally gives that result. I honestly don't remember why I stopped hardcoding it to "..." :)

To get the name style you want, instead set the prefix to 'Unknown' and make sure to not enable any of the other 'Use' buttons are checked.
