### ISSUE TITLE
Suggestion: Flat Check Notes to passive action

### ISSUE THREAD

**Issue by roguedevjake** [xdy/xdy-pf2e-workbench#347]
Quoted
`Replaced the 'Workbench Flat Check Notes' "boon" with the 'Workbench Flat Check Notes' "Equipment" which also works for npcs. To use this, manually remove the old boon where it is used, add this equipment instead.`

Suggestion: 
I recommend making it an action instead of equipment, it keeps it from cluttering the PC's inventory and keeps it roughly visible on npcs without getting in the way imo. (I am doing this already, just a broad suggestion for the ease of use for others)

**Comment by xdy** [comment]
Didn't think of actions, but, yeah, that's better. I'll try to remember to do that for the next iteration.

**Comment by xdy** [comment]
Which should probably be at the same time that I switch to the same version number as the release (e.g. 'Workbench Flat Check Notes V3.34.0'), and automatically migrate these things. (By removing the old one and then adding the new one to all actors that have the old one.)

**Comment by xdy** [comment]
Done in version 3.35.0

**Comment by xdy** [comment]
Except that I forgot to set it to passive, so I fixed that in 3.35.1
