### ISSUE TITLE
Feature Request: Macro to grow Bless Aura area (and similar spells)

### ISSUE THREAD

**Issue by Ironxxx** [xdy/xdy-pf2e-workbench#356]
Bless has a feature whereby it can grow by spending an action, 5 feet per round. It would be great if Workbench provided this functionality for the spell's active effect area.

**Comment by xdy** [comment]
Fyi @JDCalvert is considering doing this and adding it to Symon's macros (meaning that if/when it's done it'll be included with the Workbench.)

**Comment by xdy** [comment]
That macro is now included with the Workbench ("Update Aura Radius")
