### ISSUE TITLE
NaN errors when using creature level changer

### ISSUE THREAD

**Issue by grankless** [xdy/xdy-pf2e-workbench#365]
https://i.imgur.com/YJMbKvU.png

I've had this happen a few times - the DC for abilities inside Checks get turned to NaN errors instead of rescaling to anything. This is a screenshot of a Barbazu rescaled to 11.

**Comment by xdy** [comment]
Will be fixed in workbench release 4.0.0 (won't be out until pf2e system 4.0 release happens.)
