### ISSUE TITLE
Mystified items still colored

### ISSUE THREAD

**Issue by DariusWolfe** [xdy/xdy-pf2e-workbench#367]
Items that are mystified still show up with the rarity colored text.

I was able to go in and change the rarity while it was mystified, but it caught my players' attention (hence the reason it caught mine) but I feel like this subverts the mystification system a bit by drawing attention to otherwise 'innocuous' items.

**Comment by xdy** [comment]
Will be fixed in Workbench 4.0.0 (which won't be out until after pf2e 4.x is released)
