### ISSUE TITLE
Feature Request: Collapse strike and damage cards with automation

### ISSUE THREAD

**Issue by CyrixV** [xdy/xdy-pf2e-workbench#379]
Collapsing the cards of the strike & damage roll into one, as well as removing the roll buttons once used will save a lot of chat space, and improve readability.

Showing the formula as well as the modfiers above it seems like something that can be smoothed out too, as the option to click to show the roll details still remains.

![mockup](https://user-images.githubusercontent.com/111495178/185351643-a04f64ea-214c-4dc4-8630-c34749c20b26.png)

**Comment by xdy** [comment]
I'll let Dorako UI and/or DF Chat Enhancements handle this.
