### ISSUE TITLE
Recall Knowledge Function on NPCs: Levels?

### ISSUE THREAD

**Issue by Armandeus66** [xdy/xdy-pf2e-workbench#389]
If the Recall Knowledge button is enabled for NPCs, and the GM clicks the button, a message is sent to chat with several levels from 1st to 4th or so with different DCs. What do these levels signify?

**Comment by xdy** [comment]
That's the difficulty for the first attempt, second attempt, etc, with difficulty increasing by one level (standard -> hard -> very hard, etc)
See https://2e.aonprd.com/Rules.aspx?ID=563, specifically under "Additional Knowledge".
