### ISSUE TITLE
Acid Flask Unable to Roll Damage

### ISSUE THREAD

**Issue by Marloweelm** [xdy/xdy-pf2e-workbench#393]
I'm getting an error with Acid Flask where it won't roll damage because it does not have an initial dice damage, only the "bonus" splash damage. The attack works but even clicking on the damage button is disabled.

Adding dice to the damage works, but with the way alchemist has been altered now to remove crafted items and add them back from the compendium after daily crafting there's no quick fix without disabling the module.

**Comment by xdy** [comment]
I can't reproduce this on Workbench 4.0 (with the latest pf2e and foundry 10) with an acid flask I just added from the system compendium, so it seems the issue has been fixed. Please update to latest and report back if the problem remains.
