### ISSUE TITLE
Suggestion: Remove the heroPointHandler setting

### ISSUE THREAD

**Issue by mclemente** [xdy/xdy-pf2e-workbench#407]
The setting is redundant, its only function is to make a keybinding work and there's no way to activate the keybinding by accident since it doesn't have a default key set.

**Comment by xdy** [comment]
The reason it wasn't used is that I accidentally removed some code when switching to Foundry v10. But, I've now restored that, so it is used. :)
(The hero point handler is in need of another look, but for now I'll leave it as is.)
