### ISSUE TITLE
Private Spellcasting: Only private when sending to chat using icon, not cast button

### ISSUE THREAD

**Issue by Joshmvii7** [xdy/xdy-pf2e-workbench#413]
![image](https://user-images.githubusercontent.com/99048395/189199801-e26d593c-1cba-4f2b-933c-7fee86a96443.png)

When control clicking for private spellcasting, it will send to chat private if you click with the icon to the left of the name of the spell, but will not send private if you control click the cast button. Would be convenient to be able to control click the cast button since that button uses the spell slot as well.

**Comment by xdy** [comment]
That feature is already in the Workbench, see "World QoL Settings":
![image](https://user-images.githubusercontent.com/246024/189447863-752692ba-47a0-462e-a689-8bc9bc882c86.png)
