### ISSUE TITLE
Sugestion: Actions can be used on the bar

### ISSUE THREAD

**Issue by medeiros961030** [xdy/xdy-pf2e-workbench#426]
I found the integration of all actions in the pathfinder Workbench amazing, but my only improvement observation would be to be able to use these actions without having to open the sheet.

My sugestion:

Being able to drag these main actions from the tab to the macro bar

Or have some macro that could open a Hud that would appear all of them

**Comment by xdy** [comment]
See this post from apoastolov for a macro that does the latter: https://github.com/xdy/xdy-pf2e-workbench/issues/483#issuecomment-1288175768
I'm currently unlikely to do much to Skill Actions other than fixing bugs, so closing this issue.
