### ISSUE TITLE
Mystifier is removing the token's name

### ISSUE THREAD

**Issue by mclemente** [xdy/xdy-pf2e-workbench#437]
`generateNameFromTraits` returns a string with all the traits, but doesn't organize them around the name, Then, the token's name is replaced by that string https://github.com/xdy/xdy-pf2e-workbench/blob/main/src/module/feature/tokenMystificationHandler/index.ts#L32

Or the issue might be on `filterTraitList()`, which isn't concatenating the name the traits.

**Comment by xdy** [comment]
I might not understand you right, but that is the point of the method. I.e. to return a new name based on the traits the creature has (and possibly a random word and/or number), which is then used to mystify the creature.
I.e. "Dread Wisp" might become "Stubborn Abberation 89".

**Comment by mclemente** [comment]
I see. I thought it was meant to work like Token Mold's.
