### ISSUE TITLE
Suggestion: Cast Spell in Private default for NPC

### ISSUE THREAD

**Issue by LeandroMartinelli** [xdy/xdy-pf2e-workbench#438]
Hi, first of all, congratulation for the great module, good job!!
Now... there's a way to made the Cast Spell in Private the default?
Like, I really loved this option, but for time to time I forgot of the ctrl and the players know the spell before the time...
If, for NPC, we can have the option to cast spell in private by default it will be really great! 
Thanks!

**Comment by xdy** [comment]
And, should actually work in 4.5.1
What do you mean I need to test *again* after doing only a *tiny* change that can't possibly affect anything? Bah. :)

**Comment by LeandroMartinelli** [comment]
Thanks and great work!!
