### ISSUE TITLE
Feature Request: Random adjectives as an option instead of numbers for NPC Mystification

### ISSUE THREAD

**Issue by RicoTheBold** [xdy/xdy-pf2e-workbench#44]
### Is your proposal related to a problem?

Numbers as differentiators for multiple tokens of the same base actor are functional, but boring and more difficult to distinguish at a glance if the random numbers ended up similar.

### Describe the solution you'd like

By adding random adjectives instead of numbers, different creatures are represented with effectively unique descriptors that are more interesting than just numbers. The Token Mold module offers an adjective-based approach ([https://github.com/Moerill/token-mold#random-adjectives](https://github.com/Moerill/token-mold#random-adjectives)) and that part works very well, but it obviously doesn't support the trait-based mystification that you're doing.

So, for example, say I have an ancient red dragon actor I pulled from the compendium.

Today, I have Token Mold set up to replace the name of any unlinked token with a random adjective, completely obscuring what type of creature.  So if I drag the creature to the map to create a token it will just get a random name, like "Treasured" (originally I wanted it to add "creature" so it would be something like "Treasured creature" but I couldn't get Token Mold to do that and it ended up not mattering - the random adjectives are fine standalone).  My players will say, "I attack Treasured" or "I'd like to identify Treasured" instead of "I'd like to identify creature 29" and it's pretty solid. If they do identify them, though, I have to go back and manually rename the token, which is a huge hassle, particularly because the adjective is an effectively unique descriptor (the table has 4700 names) for them, so I basically just don't do it. I'll tell the players and maybe type the name of the creature in chat so they know how to spell it for their notes.

With the token mystification feature of PF2e Workbench, I'd like to be able to do something similar, but use the mystification features that are superior to complete replacement of name. So, for example, say I'm using the following NPC mystifier settings:
- Mystify by NPC Traits
- Word to prefix new name with: "Unknown"
- Word to postfix new name with: [blank]
- Add random number to name.
- No random number for unique NPCs.
- Keep token number when mystifying/demystifying.
- (Experimental) Use mystified name inside chat messages.
- No npc rarity in the name.
- Word to replace rarities greater than common with: "Unusual"
- No npc alignment traits in the name.
- No npc traits not in the above trait types.

Today, if I have an "Ancient Red Dragon token" and I mystify it I might get Unknown Dragon 31. Pretty good, my players can tell it's a dragon, but not what type. If I demystify it, it's Ancient Red Dragon 31. Great! A few years ago, before I started using adjectives, this would have been all I could ask for.

If, however, a couple of settings were added/enabled (and I disabled the random number ones):
- Add random adjective to name.
- Source of random adjective list (e.g., a rolltable)
- Position for random adjective [prefix | postfix]
- Keep random adjective when mystifying/demystifying.

I could mystify the dragon and get something like "Unknown Swaggering Dragon" and demystify it to get "Swaggering Ancient Red Dragon" instead.

With adjectives, I might even leave them on for unique NPCs, because they're just kinda fun in general.

### Describe alternatives you've considered
n/a

### Additional context

You might ask: Doesn't a list of random adjectives mean you get some deeply stupid names for your creatures? The answer is yes. It's fun, though. Sometimes the names feel very appropriate ("Tyrannous" for a boss-level monster that the party learned ordered an earlier boss around), and sometimes they're entertainingly incongruous ("Neurological" for a big spider).

**Comment by xdy** [comment]
Everything but keeping the random adjective when mystifying/demystifying will be implemented in the next release.
I gave keeping the prefix/postfix a shot, but that would require a larger rewrite of the module than I currently have the energy for, so at least for now that feature won't happen.
If you still want it, feel free to send in another request for that feature, I'll be closing this issue with the next release.
