### ISSUE TITLE
QOL Request: Consistent Manifest Link

### ISSUE THREAD

**Issue by Armandeus66** [xdy/xdy-pf2e-workbench#451]
This module changes manifest link URL with each version, and the user has to stop and click a dialog asking if they want to update the URL.

The dialog states, "this happens when the package hosting location or the author has changed." Since this is not the case, it makes it seem there is an error that I need to check on, or a dead link. A change in the manifest URL is something unusual requiring a confirmation and user awareness.

This also slows down the module update process.

I would like to request this module use the same convention as other modules and have a consistent manifest link. Thank you.

**Comment by MrVauxs** [comment]
Simply using `https://github.com/xdy/xdy-pf2e-workbench/releases/latest/download/module.json` instead of the semantically versioned URL would be great.
