### ISSUE TITLE
Bless/Inspire Courage aura effects and macros do not actually apply their respective effects to tokens in the aura.

### ISSUE THREAD

**Issue by Subwoof01** [xdy/xdy-pf2e-workbench#453]
https://user-images.githubusercontent.com/20887751/193659757-9de3f8b0-c839-4cae-b379-307c4d6e5b83.mp4

**Comment by xdy** [comment]
Seems to work for me (see my recording), was all of the following true when you tested?
```
websterguy — 07/28/2022
About to start a checklist on auras not working like i did with flanking
Checklist for auras:
- scene is active or a combat is active for the actor with the aura
- color fill will only show in an active encounter
- Map has a square grid, not gridless
- not blocked by line of sight/hearing for visual/auditory trait auras
- token auras mod removes aura visual but aura should still be functional
- the receivers of the aura must be on the same alliance as the aura giver. Party or Opposition. Neutral does not get any. 
```

https://user-images.githubusercontent.com/246024/194754042-c533536e-7008-4b15-b886-4e56c3302ebc.mp4

**Comment by Subwoof01** [comment]
I got all the buffs working now, thank you. I'm not sure which step went wrong. (I think it was the active scene/active combat step).

I assume since tokens have to be on the same side, the Bane aura does nothing other than show itself?

**Comment by xdy** [comment]
Yeah, I had already added before I noticed the 'allies only' bit, so I figured I'd let it remain. Once foundry supports affecting enemies it should start working with no changes. Hopefully. :)

Anyway, closing the issue as it works now for you.
