### ISSUE TITLE
Houserule Request: Heroic Hero Points

### ISSUE THREAD

**Issue by LonePaladin** [xdy/xdy-pf2e-workbench#457]
Everyone feels bad when you spend a Hero Point to reroll a failed check, and the new roll is worse. There's a house rule I use in my game, and I'd like to see it added as an option to allow Foundry to automate it. I should probably try to write a mini-module to handle this, but I have no idea how to do this, and if I'm asking someone for all the code necessary to make it work they're essentially writing it for me anyway.

Simply put, when you spend a Hero Point to reroll a check, if the d20 rolls a 10 or less you add +10 to the result. This doesn't change the way a natural 1 or 20 works -- you won't get a result upgrade if you roll a 10, and if you roll a natural 1 you still downgrade the result.

Some examples so you see how the numbers work.

- Making an attack roll, +7 vs. AC 15. You roll a 4 and spend a Hero Point, then roll a 3. Because the die-roll is 10 or less, the +10 kicks in. The final result is 3 + 7 + 10 = 20, a hit.
- Attempting a skill check, with a +4 bonus vs. DC 14. You roll a 9, which barely fails, and spend a Hero Point, but roll a 1. The final result is 1 + 4 + 10 = 14, which normally would succeed but because you rolled a natural 1 it downgrades to a failure. (Without the +10 it would have been a critical failure.)
- Rolling a difficult saving throw, +5 vs. DC 28. Your initial roll critically fails, so you spend a Hero Point, and roll a natural 20. The final result is 20 + 5 + 10 = 35, which would normally be a regular success, but the natural 20 upgrades it to a critical success. Without the +10, a natural 20 (total 25) would have upgraded to a regular success.
- Rolling that same save, but the Hero Point reroll is a 10 on the die. The final result is 10 + 5 + 10 = 25, which is a regular success. It is not upgraded because the +10 applies to the final result, not the die-roll itself.

**Comment by xdy** [comment]
I don't see how to do this in a sane way (and, not really in an insane way either), so I'm closing this issue as I'm unlikely to give it another try.
