### ISSUE TITLE
Macros are not working

### ISSUE THREAD

**Issue by LolipopCandy** [xdy/xdy-pf2e-workbench#464]
I made a new world to test the macros and they don't seem to be working.

This is the error I get:
![image](https://user-images.githubusercontent.com/94734833/194810067-f0a8c5b5-f8ee-431c-9341-c8f45ff70325.png)

Foundry and PF2e system version:
![image](https://user-images.githubusercontent.com/94734833/194809959-51bb8bfb-a807-467e-8ef3-f78182ac2da6.png)

Specifically here I was using Conditions Manager macro. Tried a few of the other macros and they all seem to give similar errors.

Edit: Workbench version is v4.5.1

**Comment by xdy** [comment]
It was due to a change in pf2e 4.2.5. I've changed the code in workbench 4.5.3 so the macros work if one re-adds them.
So, either wait for pf2e 4.2.6 that hopefully includes a fix for the error, or remove your current macros from workbench and re-add them from workbench 4.5.3.
