### ISSUE TITLE
Lingering Heroics Macro applying the wrong effect

### ISSUE THREAD

**Issue by LolipopCandy** [xdy/xdy-pf2e-workbench#465]
When you choose the Inspire Defense option for the Lingering Heroics macro, the actor will get the `Aura: Lingering Composition (Inspire Defense)`, however the aura itself applies the `Spell Effect: Inspire Courage` to everything within range.

![image](https://user-images.githubusercontent.com/94734833/194999160-a302f9fa-926a-4e6c-83e0-658be27d0cc1.png)

**Comment by xdy** [comment]
Haven't had a chance to try it yet, but I think Symon pushed a fix for this earlier.
