### ISSUE TITLE
Macro Bug - Request Checks Menu

### ISSUE THREAD

**Issue by roguedevjake** [xdy/xdy-pf2e-workbench#477]
When clicking a check it says " if the dc is left blank or invalid then a check with no DC will be posted", however doing this throws an error notification of "please input a number in the DC field" and no check is posted.

**Comment by xdy** [comment]
The macros are in a weird place, I just package them up from Symon's repository at https://gitlab.com/symonsch/my-foundryvtt-macros/-/tree/main/PF2e (with permission of course).
Probably better to ping Symon in the foundry discord or make an issue at the aforementioned gitlab repo as he doesn't read issues here.
