### ISSUE TITLE
Autorolling spells doesn't heighten them

### ISSUE THREAD

**Issue by NikolasTzimoulis** [xdy/xdy-pf2e-workbench#478]
It rolls damage as if you were using the lowest possible level of the spell.

**Comment by xdy** [comment]
Yeah, the old way of telling the system what level to use apparently no longer works. I tried to fix it yesterday, but, no luck.
I'll take another look at it over the weekend.

**Comment by NikolasTzimoulis** [comment]
No rush, take your time.
