### ISSUE TITLE
Missing Macros

### ISSUE THREAD

**Issue by InstantZzz** [xdy/xdy-pf2e-workbench#479]
Hi

I'm using Foundry V10.288, Pathfinder 2E V4.2.6, and PF2E Workbench V4.5.5
On this combination, I have lost some of my macros.
Noticeably I am now missing my 2-Action Heal and Harm macros. If any other macro is missing, I have not noticed.

**Comment by xdy** [comment]
Those aren't really needed with the latest version of the system as the heal and harm spells have been improved.
Therefore they were never updated to work with foundry v10 and are no longer included with the Workbench.
If, that said, you still want to use them you will most likely have to upgrade them to v10 yourself, if so you can find them here: https://gitlab.com/symonsch/my-foundryvtt-macros/-/tree/main/PF2e/V9

**Comment by InstantZzz** [comment]
Okay, thank you.
