### ISSUE TITLE
Send To Chat Feature - Public Chat

### ISSUE THREAD

**Issue by ChaseDonnally** [xdy/xdy-pf2e-workbench#499]
I'm loving the new Send to Chat feature for items and features. Could it be set up so that it defaults to always send to chat as a "Public Roll", regardless of whatever the GM's default rolling method is? Maybe there could be a setting for this, but I think it makes sense for the default to be public.

Thanks!

![image](https://user-images.githubusercontent.com/47797620/197380111-97e30342-14f2-4261-a626-d030a3db8644.png)

**Comment by xdy** [comment]
Wrong module. :)
Send to Chat is from Dorako UI.

**Comment by ChaseDonnally** [comment]
Woops! Sorry about that, misread which module changelog I was looking at.
