### ISSUE TITLE
[Feature] Add Escape to the possible skill actions

### ISSUE THREAD

**Issue by manuel-hegner** [xdy/xdy-pf2e-workbench#510]

**Comment by xdy** [comment]
Next release will have basic support for escape (as in, supports Acrobatics and Athletics rolls, but not Unarmed, and no MAP buttons.)
I'll return to this later.

**Comment by xdy** [comment]
See also #531

**Comment by xdy** [comment]
I just returned to it. :)
Fixed in 4.31.0
