### ISSUE TITLE
Workbench animates movement of tokens teleported by the Multilevel Tokens module

### ISSUE THREAD

**Issue by pedrogrullada** [xdy/xdy-pf2e-workbench#516]
Foundry v10.288, pf2e v4.3.1

To replicate, simply enable multilevel tokens and pf2e-workbench, create two connected text-boxes with multilevel tokens and drag a token into one of them. You should see that the token is animated as if it were dragged to the location, instead of teleported (regardless of having movement animation off in your multilevel drawing settings).

Here are some gifs to illustrate the problem:
![example_workbenchtrue](https://user-images.githubusercontent.com/103401186/198753158-f4701654-66b2-4736-b2ca-77a9ef6b56fc.gif)
**Workbench On**

![example_workbenchfalse](https://user-images.githubusercontent.com/103401186/198753171-a0ebbca0-5ff7-49cc-9b2a-a1f203ad2069.gif)
**Workbench Off**

**Comment by xdy** [comment]
Have you changed the value of 'World QoL Settings'/'Change to alter token movement speed' from the default value of 6?
If so, change back to 6 and try again.
If not, I was wrong about 6 being the default...

**Comment by pedrogrullada** [comment]
> Have you changed the value of 'World QoL Settings'/'Change to alter token movement speed' from the default value of 6? If so, change back to 6 and try again. If not, I was wrong about 6 being the default...

It's still 6, I didn't even know that was a setting!

**Comment by Tanick42** [comment]
Can confirm same.  Unchanged speed volume from 6, and have the same issue.
