### ISSUE TITLE
Recall Knowledge skill action rolls from the skill sheet actions will never have any REs applied to it

### ISSUE THREAD

**Issue by Cerapter** [xdy/xdy-pf2e-workbench#518]
This is not the issue detailed in #517 .

Even if the aforementioned PR is merged, the issue will still persist as the Recall Knowledge slug is `recall-knowledge-lore`. The system looks for `action:recall-knowledge`, which will never match the generated `action:recall-knowledge-lore`.

The slug is this way to match up the action item whose slug _is_ `recall-knowledge-lore`.

To fix this, either a dirty fix can be implemented à la Earn Income, a new 'action slug' field can be added to represent this difference, or this can be changed straight in the PF2E system code (yeah, nah).

**Comment by xdy** [comment]
Skill action were removed in 5.32.0
