### ISSUE TITLE
Escape action on Skill Actions is applying armor check penalty despite meeting STR requirement.

### ISSUE THREAD

**Issue by Joshmvii7** [xdy/xdy-pf2e-workbench#531]
![image](https://user-images.githubusercontent.com/99048395/199730340-900cc278-7b07-4ab8-9bf3-8f4b784290b4.png)

**Comment by xdy** [comment]
Both Skill Actions and Basic Action Macros use uses the pf2e system Escape action, so this needs to be fixed in the system if this still occurs. Closing issue.
