### ISSUE TITLE
[Request] Level Range in Loot Gen

### ISSUE THREAD

**Issue by jasonckramer** [xdy/xdy-pf2e-workbench#555]
Add ability to generator loot from a level range.

**Comment by xdy** [comment]
Closing issue as the Loot Generator macro is made by Symon, I just include it in the Workbench as a convenience. Instead, ake an issue at https://gitlab.com/symonsch/my-foundryvtt-macros/-/issues or ask him in the community discord at https://discord.gg/pf2e
