### ISSUE TITLE
Players can't see skill actions

### ISSUE THREAD

**Issue by gylfii** [xdy/xdy-pf2e-workbench#562]
I'm new to foundry and am running the beginner box with a few friends. I setup pf2e workbench and then the skill actions. Then toggled the eye icon on, but the players don't see them.
Here is the dm point of view from foundry:
![1  dm view](https://user-images.githubusercontent.com/60700749/203839623-8c8826f6-9d57-40fe-95ba-fb9f5aeb1561.PNG)
Then here is the player point of view from their browser:
![2  player view](https://user-images.githubusercontent.com/60700749/203839700-dfecf962-78a7-4de6-87e2-51c734ce68d7.PNG)

Is there any player option that I missed, could this be a bug. Maybe it's due to other addons that could screw with that specific one.
Any ideas or suggestion on what could be the problem?

**Comment by xdy** [comment]
The skill actions are a client setting, so each user has to enable them in their own browser.
