### ISSUE TITLE
[Bug] Treat Wounds macro

### ISSUE THREAD

**Issue by roguedevjake** [xdy/xdy-pf2e-workbench#580]
The XDY treat wounds maco fires off a healing roll (and damage for risky surgery) for each target instead of just one for all targets. Should be an easy fix as the treat wounds macro in the PF2e system does one roll for all targets.

(this is how it works for ward medic btw, one roll all targets get that result. But it also keeps chat clean/easy to read. Also really nice with PF2e Damage Target :) )

**Comment by xdy** [comment]
I just include this macro https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Treat%20Wounds%20and%20Battle%20Medicine.js in the Workbench compendiums.
I can't recall who it is that maintains that, but ask Symon and he should know.
