### ISSUE TITLE
[Bug] XDY Basic Actions Macro

### ISSUE THREAD

**Issue by roguedevjake** [xdy/xdy-pf2e-workbench#581]
Holding shift doesn't hide or show the roll dialogue window (depending on default state). 

(it does for the buttons in the symon quick skill actions macro so it might be worth looking there to see how)

**Comment by xdy** [comment]
The problem is that BAM doesn't actually roll dice as such, it uses the system action macros which do not have the option to open the roll dialogue window (it doesn't pass along skipDialog so I can't set it manually either.) Unless this is changed in the system there isn't much I can do about this.
