### ISSUE TITLE
Inspire Courage / Defense Auras end and break after one round

### ISSUE THREAD

**Issue by Failtier** [xdy/xdy-pf2e-workbench#584]
Hi,
when using the Inspire Aura from the Workbench compendium, the aura will usually only last for one round and then break, giving me different critical errors such as this one:

> Uncaught (in promise) Error: The key C392brWOs1PcTZ2X does not exist in the EmbeddedCollection Collection
> [No packages detected]
>     at EmbeddedCollection.get (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/collection.mjs:119:13)
>     at ServerDatabaseBackend._deleteEmbeddedDocuments (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:5710)
>     at ServerDatabaseBackend.delete (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/backend.mjs:214:31)
>     at async Semaphore._try (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:101:17)

Reloading the world usually solves the issue until the aura breaks again. Also, it seems like there is no way to really sustain the aura in constrast to the Bane/Bless aura.

Thanks!

**Comment by xdy** [comment]
This works on my machine, except when it doesn't...
It's been noted in the discord that this occasionally happens for any auras for some people, so it's a system (or possibly foundry) problem that I can't do anything about, so closing this issue.
