### ISSUE TITLE
Add an optional feature that handles flat checks

### ISSUE THREAD

**Issue by xdy** [xdy/xdy-pf2e-workbench#59]
Like, check if target is one of hidden, invisible, etc that gives a flat check.
If so, either roll a flat check along with attack, or if that seems difficult, add a flat check button to the attack chat message.
I.e. in the first case the workflow would be:
Pick target, roll, which rolls a flat check the result of which is added to the message (with gm visibility), the gm tells you if you hit.
I.e. in the latter case the workflow would be:
Pick target, roll, if a hit, click the 'flat check' button which rolls a blind gm roll, he tells you if you hit.

Maybe differentiate between the different types of flat checks, some don't really need to be blind rolls.
Or, maybe, always do open rolls for flat checks?

**Comment by roguedevjake** [comment]
I have currently "solved" this by creating an action with rule elements checking for the correct conditions onto PCs and NPCs and (note rule element).

Not perfect, but it works well (I have also been using effects to grant conditions, so stuff like mist form elixir works as well)

`{"key":"Note","selector":"attack","text":"<p><strong>Hidden:</strong> @Check[type:flat|dc:10]</p>","predicate":{"any":["target:condition:hidden","target:condition:invisible","self:condition:blinded"]}}`

and

`{"key":"Note","selector":"attack","text":"<p><strong>Concealed:</strong> @Check[type:flat|dc:5]</p>","predicate":{"any":["target:condition:concealed","self:condition:dazzled"]}}`

On an action item called "flat check operator".

**Comment by xdy** [comment]
Yeah, I've been doing something similar though I put it on a feat I gave out as a campaign feat:
```{"key":"Note","selector":"attack","text":"<p class='compact-text'><strong>Concealed</strong> The target is concealed, make a @Check[type:flat|dc:5|name:Concealed Flat Check|showDC:all]</p>","predicate":{"all":["target:condition:concealed"],"not":["self:feat:blind-fight"]}}```
```{"key":"Note","selector":"attack","text":"<p class='compact-text'><strong>Hidden</strong> The target is hidden, make a @Check[type:flat|dc:11|name:Hidden Flat Check|showDC:all]</p>","predicate":{"all":["target:condition:hidden"]}}```
```{"key":"Note","selector":"attack","text":"<p class='compact-text'><strong>Undetected</strong> The target is undetected, make a @Check[type:flat|dc:11|traits:secret|name:Hidden Flat Check|showDC:all]</p>","predicate":{"all":["target:condition:hidden"]}}```

Probably worth including in the module, so I'll combine ours onto one item and include in the module if you don't mind?
If you have more suggestions for note RE:s that would be good to have on a character, do send them in, might as well collect them in one place.

**Comment by roguedevjake** [comment]
Yeah ofc, I just realised in my haste I had it be a DC11 flat check -laughs-. 

Having the ability to ignore via stuff like blind fight is also good (be useful to include for stuff like cat's eye elixir, maybe tracking via a meta trait for stuff that ignores or modifies?)

Hey would you know if there was a way to assign a value to a granted item? Would make it a lot cleaner to automate ability/spell effects.

**Comment by xdy** [comment]
Nice. I'll pull together the ones we have then and put in an item of some sort for next release.

As for GrantItem, I haven't really played around with that I'm afraid, so, not a clue.

**Comment by xdy** [comment]
I had noted to myself to try to figure out how to do these:
* Note on cast a spell if Stupefied about Flat Check 5+Stupefied. (Or, really, on every spell, but I don't think that is doable.)
* Note about flat check when skill/action is used if Grabbed, if the check has manipulate trait.
* Note about flat check when skill/action is used if Deafened, if the check has auditory trait.
* Note on all exploration activities about them being impossible if Fatigued.
* Note about checks with Concentration being impossible if Fascinated.
* Note to GM and self about not being able to choose one's own actions if Controlled or Confused.

Haven't looked at doing them though, so they might not be possible.

**Comment by xdy** [comment]
And, I just noticed the last of my note RE:s is broken. It talks about Undetected, but checks for condition:hidden. :)
A shame that Undetected is not a condition. Ah well.

**Comment by xdy** [comment]
As the notes are now in 2.46.0 I think I'll close this issue. If more note REs are added later I'll do them in another issue.
