### ISSUE TITLE
Better language sort for basicActionMacro

### ISSUE THREAD

**Issue by Far2Casual** [xdy/xdy-pf2e-workbench#602]
https://github.com/xdy/xdy-pf2e-workbench/blob/bbdc509743ad80475368ec4044db37d76dcdec46/src/module/feature/macros/basicActionMacros.ts#L348

We would advise using this instead, as it would improve sorting using language special characters:
`sort((a, b) => a.localeCompare(b, locale))`

![image](https://user-images.githubusercontent.com/63196064/210526844-be6d6640-6bd6-41fc-ba81-2c4ea3d4194c.png)

**Comment by rectulo** [comment]
![image](https://user-images.githubusercontent.com/98176148/210545622-807fddde-3ed8-4538-8f78-75992c26d543.png)

**Comment by rectulo** [comment]
Thanks for all your efforts.
