### ISSUE TITLE
Prevent "Dropped" items from counting towards total bulk

### ISSUE THREAD

**Issue by shemetz** [xdy/xdy-pf2e-workbench#605]
They should count as 0 bulk, regardless of their carried/worn bulk.

Screenshot of bug:

![image](https://user-images.githubusercontent.com/6516621/211068955-968c5207-6518-4315-a72f-937e1381e106.png)

Feel free to close this if you think [the system should support this feature directly](https://github.com/foundryvtt/pf2e/issues/5528), rather than this module.

**Comment by xdy** [comment]
I would prefer if the system handled this, yeah. (I call the system isEncumbered to see if the actor is encumbered, and would prefer to not reimplement the system encumbrance code.)

**Comment by shemetz** [comment]
well, the system decided not to implement this at all (not until the dropped thing creates an actual item on the canvas), so it's probably not going to happen.
