### ISSUE TITLE
Magic Missile macro deals 1d6 damage per action instead of 1d4

### ISSUE THREAD

**Issue by Fraxinus1753** [xdy/xdy-pf2e-workbench#606]
When cast through the Workbench macro, Magic Missile deals 1d6 per action instead of 1d4.

**Comment by xdy** [comment]
Symon has fixed this in https://gitlab.com/symonsch/my-foundryvtt-macros/-/tree/main/PF2e, and I included the fix in Workbench 4.30.1, so closing issue.
