### ISSUE TITLE
Persistent Damage - Auto Apply Persistent Damage

### ISSUE THREAD

**Issue by sturteva** [xdy/xdy-pf2e-workbench#618]
With a recent update to the PF2e System, the Persistent Damage is handled by the system instead of the PF2e Persistent Damage Module.  Unfortunately, with that change the Workbench Client Automation setting that auto-applied the damage is no longer working. 
![image](https://user-images.githubusercontent.com/32139677/213036289-cfbcf0d7-1d62-482e-9910-b16ca6d0e611.png)
![image](https://user-images.githubusercontent.com/32139677/213035862-1b5da5d5-acc9-47b4-adf0-1efa784df8ee.png)
Alas, the Mitflit, Useless Morcrs(7) did not take any automated damage.

Don't know if it's in-scope for this issue, but having it auto-roll the recovery check as well would be super useful.

**Comment by xdy** [comment]
Seems to work for me. Try again using the latest version of foundry (10.291), system (4.6.8) and Workbench (4.34.0)
![image](https://user-images.githubusercontent.com/246024/213869254-42c96811-045e-4cd9-9fe2-9119a99072ee.png)

![image](https://user-images.githubusercontent.com/246024/213869261-e237512b-184e-42b5-9505-54ea9c4de6f4.png)

**Comment by xdy** [comment]
Closing as non-reproducable, open a new issue or ask on the discord if it's still an issue for you on the latest version with no other modules enabled.
