### ISSUE TITLE
Demoralizing enemy's (not taking account for immunity and language)

### ISSUE THREAD

**Issue by WaterpoloBlock** [xdy/xdy-pf2e-workbench#619]
I'm not sure if this is a Core issue or Work Bench.

![Demoralize_Example](https://user-images.githubusercontent.com/73310678/213066338-6b3b3111-d299-4f2c-8dec-b34908c2d9d1.png)

But when doing mental effects, like Demoralize.  The system doesn't take into account for Immunity's (The Zombie Shambler) or the fact that they don't share a language (Giant Fly)

**Comment by xdy** [comment]
Closing as this is a system issue. Might be worth reopening on the system github, it sure would be handy if the system handled it.

**Comment by WaterpoloBlock** [comment]
When you say system do you mean Foundry VTT it self, or the PF2e game system? 

Want to make sure so I open an issue in the correct Github.
