### ISSUE TITLE
Increase max number of focus points as a home brew option?

### ISSUE THREAD

**Issue by Mermut** [xdy/xdy-pf2e-workbench#630]
I've been looking at the Mythic 2e stuff, and they use focus points (up to 6 total) for the mythic power pool...
Just like there's an option to increase the max number of hero points, I'm wondering if it would be possible to add something to increase the max number of focus points as a home brew option.

**Comment by xdy** [comment]
I'll include an effect 'Effect: Change Focus Point Maximum' that you can add to characters that should have a different cap to Focus Points (change the counter value to change the cap.)
