### ISSUE TITLE
[Request] Descriptions of macros -- what do they do?

### ISSUE THREAD

**Issue by LonePaladin** [xdy/xdy-pf2e-workbench#640]
It would be really helpful to have a description somewhere of the macros in the compendium "Symon-provided macros". What does "Adjust Merchant Prices" do? What is the difference between "Advanced Countdown", "Countdown-Cooldown", and "Modded Countdown Cooldown"? What about "Actions With Potency", "QuickSkillActions", and "Skill Action Dialog"?

Several seem to have overlapping usage just going by the names -- there are four related to Battle Medicine -- and the code doesn't include an explanation of their purpose.

**Comment by xdy** [comment]
I just distribute those macros with the Workbench, they're from Symon's github repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/tree/main/PF2e , the macros included is always what's on that repo at that moment, it's fully automated.
Most/all of them do include descriptions at the top of the files on the github repo, which is as good as I think the documentation of them will get.

**Comment by LonePaladin** [comment]
:\

That's okay, I guess. The macros themselves don't have any descriptions within Foundry, which was where I looked first.
