### ISSUE TITLE
Treat Wounds Macro to include Wounded condition removal on success.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [xdy/xdy-pf2e-workbench#643]
RAW if there is a success with treat wounds it should remove the wounded condition. so it would be nice if the macro included that upon success and crit success. 

https://2e.aonprd.com/Actions.aspx?ID=57

![image](https://user-images.githubusercontent.com/62528192/216772542-ca3177f7-646e-4194-b910-d8f50cf59c1c.png)

not sure if this is the right place for it to request that but id really appreciate it.

**Comment by Symon-S** [comment]
Not a workbench thing
