### ISSUE TITLE
Feature Request:  Make option on a Prototype Token to Mystify on arrival

### ISSUE THREAD

**Issue by galaara98** [xdy/xdy-pf2e-workbench#65]
I would like to be able to have something like Monks Active Tiles create an actor that is already mystified.

**Comment by xdy** [comment]
This one is unlikely to happen as I, quite frankly, have no clue how to do it.

**Comment by xdy** [comment]
I guess once #186 is done I could store a flag on the actor like 'mystifyOnCreate'.
But, the main problem remains, the ui for setting the flag. Hook into the prototype token sheet and insert a checkbox somewhere? Somehow?

**Comment by xdy** [comment]
Not likely to ever be done, closing issue.
