### ISSUE TITLE
Basic Action Macro: Avoid Notice activity is public by default, should be blind GM roll

### ISSUE THREAD

**Issue by weepingminotaur** [xdy/xdy-pf2e-workbench#650]
If you're avoiding notice during exploration, your Stealth check shouldn't be visible to you, the player. This is a request to make the Avoid Notice basic action a blind GM Roll.

**Comment by xdy** [comment]
Basic Action Macros simply calls the system macros, so this needs to be changed in the system. 
As a workaround you can always press ctrl when clicking the button, this does a blind/secret roll.
