### ISSUE TITLE
FR: de-slugify lores in RK macro

### ISSUE THREAD

**Issue by esheyw** [xdy/xdy-pf2e-workbench#651]
Love the RK macro, but a very minor cosmetic improvement would be replacing stuff like ![](https://i.imgur.com/mQttacQ.png) with `Underworld Lore`

**Comment by xdy** [comment]
That macro lives on Symon's repository (https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Recall_Knowledge.js) and is maintained by Allalinor, I just include it in the Workbench for convenience. Either ping Allalinor ッ#2663  or Symon S.#4655 on the discord, or make an issue on Symon's repo above. If they fix this it will automatically be included in the next release of the Workbench and thus updated in your world.
