### ISSUE TITLE
Bug? Regression? BM immunity effects use Actor art instead of Token art

### ISSUE THREAD

**Issue by esheyw** [xdy/xdy-pf2e-workbench#652]
Back in v9, it used the token art. This was much better, IMO, because it was reliably square and uniform. My actor portraits are anywhere from perfectly square to very tall, and the very tall ones get akwardly squished on the token hud and effects panel.

**Comment by xdy** [comment]
That macro lives on Symon's repository (https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Treat%20Wounds%20and%20Battle%20Medicine.js) and is maintained by Darkim, I just include it in the Workbench for convenience. Either ping darkim#7921 or Symon S.#4655 on the discord, or make an issue on Symon's repo above. If they fix this it will automatically be included in the next release of the Workbench and thus updated in your world.
