### ISSUE TITLE
Skill Actions displaying for Gamemaster but not for players

### ISSUE THREAD

**Issue by artlawry** [xdy/xdy-pf2e-workbench#655]
I ran a group of friends through a pf2e adventure last night and while I could see skill actions as intended on the actions tab of their character sheets, they could not. I restarted the world, ran system and module upgrades, and had them each relog with no success.

**Comment by itsmeitmohthy** [comment]
Same. None of my players can see the skill actions.

**Comment by xdy** [comment]
This is a client setting, which means that all users must set it on their own client.
Or, the GM can use something like the module Force Client Settings (https://gitlab.com/kimitsu_desu/force-client-settings) or Monk's Player Settings (https://github.com/ironmonk88/monks-player-settings) to force this setting to enabled for the players.
