### ISSUE TITLE
Treat Wounds and Battle Medicine macro - Visible immunity

### ISSUE THREAD

**Issue by jasonckramer** [xdy/xdy-pf2e-workbench#656]
Hello!

It would be great if the immunity effect showed to whom a PC is immune from when using the **Treat Wounds and Battle Medicine** macro. Currently the macro is handling immunity correctly, it is just not obvious to whom the immunity arose.

Thank you for your consideration!

**Comment by xdy** [comment]
That macro lives on Symon's repository (https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Treat%20Wounds%20and%20Battle%20Medicine.js) and is maintained by Darkim, I just include it in the Workbench for convenience. Either ping darkim#7921 or Symon S.#4655 on the discord, or make an issue on Symon's repo above. If they fix this it will automatically be included in the next release of the Workbench and thus updated in your world.
