### ISSUE TITLE
Treat Wounds Skill Action is missing with Natural Medicine

### ISSUE THREAD

**Issue by Pyroman2xxx** [xdy/xdy-pf2e-workbench#665]
The Natural Medicine feat description says that you can use Nature instead of Medicine to Treat Wounds which, I believe is intended to mean that you would not need to be trained in Medicine if you are trained in Nature.

The Skill Action sheet does not seem to recognize this. Is it possible to add such a check into the Skill Action system?

**Comment by xdy** [comment]
Sure, I'll add that in the next release, along with similar support for Chirurgeon (that can use crafting). Do note that the system Treat Wounds macro which gets called doesn't automatically select nature (or crafting), so you still have to select the proper skill in the popup. (Might be possible if/when the system's Treat Wounds macro is improved.)
