### ISSUE TITLE
Sheets do not display bulk values

### ISSUE THREAD

**Issue by magispitt** [xdy/xdy-pf2e-workbench#666]
![image](https://user-images.githubusercontent.com/96706608/221322494-5fb72cb8-f70a-4932-b24c-97e585ac2481.png)
NPCs do not currently track bulk, as seen above (Troubadour from the NPC Gallery).

When using the PF2e Workbench module, there is an option to apply encumbrance (see images below of the option and an NPC (camel) token encumbered after enabling said option); I assume this implies that bulk can be tracked on NPCs sheets.

![image](https://user-images.githubusercontent.com/96706608/221322537-d3a77cdf-aa30-4aa6-87a4-32f77dda7600.png)
![image](https://user-images.githubusercontent.com/96706608/221322542-dc58c41b-ded8-458d-b98b-1bbdaa75025e.png)

Vehicle sheets do track bulk; the total bulk carried by the vehicle, however, is not displayed (see image below of a cart with several items; the bulk of each individual item is visible, but not their aggregate bulk).

![image](https://user-images.githubusercontent.com/96706608/221324842-78ddcf10-4172-4537-a5e9-37973f01299d.png)

**Comment by xdy** [comment]
The module uses the system code for this, which doesn't track bulk for npcs. I.e. if you want this feature, make an issue for it on the pf2e system instead. If/when that gets added it should - hopefully - automatically function in the Workbench.
