### ISSUE TITLE
Localisation breaks RK buttons

### ISSUE THREAD

**Issue by Far2Casual** [xdy/xdy-pf2e-workbench#674]
https://github.com/xdy/xdy-pf2e-workbench/blob/aac0222d9ed6238680e413f108b8b1d8b1dab9a2/src/module/feature/qolHandler/index.ts#L142

At this line, you construct a button using the translated term for skills, which does not work. The english slug of the skill should be used instead.

**Comment by xdy** [comment]
You're right, but unfortunately that string is all I've got. I set pf2e to french, and, this is what I have to choose from:
```<div class="recall-knowledge section-container">
	<div class="section-header">
		<h4>Se Souvenir</h4>
		<button type="button" class="breakdown">Essais</button>
	</div>
	<div class="section-body">
			<div class="tag-legacy identification-skills" title="42/44/47/52">
				<ul>
						<li>Occultisme</li>
				</ul>
				42 (normal)
			</div>
		<div class="unspecified-lore tag-legacy" title="40/42/44/47/52">
			Connaissance non spécifique 40 (facile)
		</div>
		<div class="specific-lore tag-legacy" title="37/40/42/44/47/52">
			Connaissance spécifique 37 (très facile)
		</div>
	</div>
</div
```
The original skill name is nowhere to be seen. (It's the same in german.)
I don't want to hardcode a list of the skills for each creature type as that is likely wrong for some creatures.
So, I don't see a reasonable way to fix this for other languages (well, except for translators not translating the skill name, which would make the buttons work, but wouldn't be very helpful for people who don't speak english.)

**Comment by xdy** [comment]
This feature broke irrevocably in a recent pf2e update.  (As in, too much work to fix it given the excellent Recall_Knowledge macro Darkim wrote, that is also included in the Workbench.)
So, closing this issue.
