### ISSUE TITLE
Request: "auto-refresh" after update as a setting

### ISSUE THREAD

**Issue by jasonckramer** [xdy/xdy-pf2e-workbench#678]
Would it be possible to make the auto-refresh after update an option in the settings? Thanks!

**Comment by jasonckramer** [comment]
If you have updated the PF2e system & Workbench, then load up the world, the system starts updating, and Workbench forces a refresh. I suspect at some point that may cause an issue with the system update.

**Comment by xdy** [comment]
Closing this issue as the workbench no longer autorefreshes (it keeps track of and reloads hooks as needed depending on changed settings.)
