### ISSUE TITLE
Auto-rolled spell damage/healing isn't higher by heightened spells

### ISSUE THREAD

**Issue by shemetz** [xdy/xdy-pf2e-workbench#679]
I think this is a regression - it was apparently fixed in https://github.com/xdy/xdy-pf2e-workbench/issues/478

versions:  PF2E 4.8.2, Workbench 4.48.0

Screenshots (each time I first rolled the spell from the sheet and then clicked the "damage" button once more.  in the first image, the first healing is incorrect and the second one is correct)

![image](https://user-images.githubusercontent.com/6516621/222725062-5342ca11-0bb1-4560-b22c-ab57c094d66e.png)

![image](https://user-images.githubusercontent.com/6516621/222725078-1cf319a7-2dc6-4a8e-b46c-e9817aa1c05e.png)

**Comment by xdy** [comment]
Works for me on 4.49.4
![image](https://user-images.githubusercontent.com/246024/222752549-13fd248c-4117-4072-b0c1-ef0ed91051a0.png)

Could you test again on the latest version?

**Comment by shemetz** [comment]
Updated PF2E;  This issue was solved for me, and another was created :D
