### ISSUE TITLE
[Bug] If a character has multiple sources of persistent damage, Workbench's auto-damage only auto-applies the first one.

### ISSUE THREAD

**Issue by Malkyn99** [xdy/xdy-pf2e-workbench#686]
Title. When a character had both persistent acid and fire damage, both were rolled at the end of their turn but only the first one rolled applied.

**Comment by xdy** [comment]
Hmm. Works for me:
![image](https://user-images.githubusercontent.com/246024/224475533-a29f05a5-1bfd-428d-9716-aa0532d217ea.png)

**Comment by xdy** [comment]
Closing issue, open another if you can reproduce it with no other modules and the latest version of the system.
