### ISSUE TITLE
[Bug] PF2e Workbench breaks the Persistent Damage condition

### ISSUE THREAD

**Issue by Simon-Magnus** [xdy/xdy-pf2e-workbench#687]
Natively to Foundry's PF2e system, dragging the 'Persistent Damage' condition on to a character opens a prompt allowing the user to input a manual damage value. This is important for when spells like Produce Flame or Acid Arrow are heightened, as they do more damage than they did initially. In the image, that is the lower 'Persistent Damage', with the little suitcase icon. The one with a pre-established damage value will always roll 1d4 or whatever the default amount is.

![image](https://user-images.githubusercontent.com/127071018/223012540-37ffb552-5bd4-4951-ac29-76f92d6f4480.png)

A game world that has had PF2e Workbench installed no longer has this functionality - dragging 'Persistent Damage' onto a character will create a condition with no automation attached. The prompt no longer comes up. This issue persists even if PF2e Workbench is deactivated. I was able to confirm this by creating a new game world in the PF2e system and dragging the condition onto a test character, causing the prompt to come up. After activating PF2e workbench, the prompt stopped coming up, and it did not return after deactivating.

**Comment by xdy** [comment]
The steps I used to try to recreate the base behaviour you talke about above:
Uninstall and reinstall pathfinder 2e, make and launch a new world with no modules, create scene, drag fifth-level ezren to that scene from compendium tab , give him produce flame, cast it, drag 'Persistent Damage' from chat to token, it adds Persistent Damage with no value (i.e. no prompt). I get the same result if I drag to an open character sheet. Opening the HUD and clicking persistent damage there does nothing.
What did you do to make it happen?
![image](https://user-images.githubusercontent.com/246024/223185794-79f13788-828b-4167-9c41-be26f3ecd52d.png)

**Comment by Simon-Magnus** [comment]
I swear it was working yesterday, but now I also cannot repeat the intended behaviour! I basically just created a new world in PF2e, made a 'test dummy' PC, put it on a 'test arena' scene, and dragged 'Persistent Damage' on it as you describe. This brought up a pop-up window with fields I could type into. I then turned each module on and off individually to confirm it was turned off by Workbench.

I don't know why it's different now, but this morning when I try, I get the same result you do.

The PF2e devs in the Foundry discord were very sure that the functionality I describe is supposed to happen, so I'm going to go back to them and prod them again.
