### ISSUE TITLE
Disable Russian localization

### ISSUE THREAD

**Issue by Vesselchuck** [xdy/xdy-pf2e-workbench#688]
In the Russian-speaking PF2e community, there are several variations of the translation of the system. The two main ones are the official and fan translations. The latter was used in the translation of this module, and now it is forcibly included for those who were quite happy with the module in the original.

It is also interesting that for the Russian-speaking PF2e community, there are at least three modules with translations of the system which also translate modules. In any of these modules, it would be possible to add this translation, so as not to force the others to see so loosely translated terminology that it is literally not clear what it means.

Is it at least possible to get an option in the module settings that would allow you to disable this strange translation into Russian and use it in English?

**Comment by xdy** [comment]
Yeah, I was a bit surprised when I got the translation as I remember someone mentioning the russian translation earlier, but I figured maybe that translation module had given up on updating.
I guess I should point the translator to that module.
@Vesselchuck Do you know which module the translation should be submitted to?

**Comment by Vesselchuck** [comment]
The interesting thing is that this **DoctorDankovsky**, who submitted the translation to this module, has his own Russian translation module. Just one of the three I described earlier. His module has a translation of **xdy-pf2e-workbench**, but for some unknown reason he decided to add it here too.

Here is a link to his Russian translation module:
https://gitlab.com/gnuraco/pf2r/-/tree/master

**Comment by xdy** [comment]
@DoctorDankovsky see above, it seems the situation with russian translation is a bit complicated. To make things easier for myself I'll remove russian language support from this module and encourage you to add it to either your module or to Phenomen's module (https://github.com/phenomen/foundry-vtt-ru), or whatever the third module mentioned above is.
