### ISSUE TITLE
Feature Request: Mystifying items when reaching 0 hp should have minimum level.

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [xdy/xdy-pf2e-workbench#690]
instead of mystyfying everything from lvl 0 i suggest being able to select a minimum level. so that when you get players who are checking downed creatures they arent constantly trying to identify low value items. and maybe if we have one for each level we could change the minimum value so that when players level up they arent constantly identifying items that are beneath their level.

**Comment by xdy** [comment]
Added in next release. Also added setting for minimum rarity.

**Comment by ThingsCouldGetDicey** [comment]
thank you that was super quick!

**Comment by xdy** [comment]
I thought I couldn't 🧠 any more after work today, but, I was wrong. :)
(Also, it was something I had intended to do soon anyway, specifically to enable "don't mystify on-level common items".)
