### ISSUE TITLE
Recall Knowledge Output Skill names

### ISSUE THREAD

**Issue by xanstin** [xdy/xdy-pf2e-workbench#694]
If the token name doesnt match the character sheet full name, the skills dont show up properly. Example case character sheet name was "Cade Goodberry" and Token Name was just "Cade". Once Character Sheet name was set to just "Cade" it displayed properly.

![image](https://user-images.githubusercontent.com/26841771/224514392-93f59c9d-8bd2-4382-b775-acf74662ddbe.png)

**Comment by xdy** [comment]
That macro lives on Symon's repository (https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Recall_Knowledge.js) and is maintained by Darkim, I just include it in the Workbench for convenience. Either ping darkim#7921 or Symon S.#4655 on the discord, or make an issue on Symon's repo above. If they fix this it will automatically be included in the next release of the Workbench and thus updated in your world.

**Comment by xanstin** [comment]
It was fixed on his end after I reported it, not sure if any action is needed on this side. https://gitlab.com/symonsch/my-foundryvtt-macros/-/issues/32#note_1326688325
