### ISSUE TITLE
XP Miscalc

### ISSUE THREAD

**Issue by Nuku** [xdy/xdy-pf2e-workbench#695]
I think it gets confused if there are more than 4 PC people. A low encounter battle tried to give 100 xp, which is assuredly not right.

**Comment by xdy** [comment]
Did you send this to the wrong module? The Workbench doesn't do anything having to do with xp calculation. Are you using the macro from https://gitlab.com/Ustin/pf2e-tweaks perhaps? Or the system one (found in the PF2e Macros compendium)?

**Comment by Nuku** [comment]
Oops! Yep, wrong place, sorry.
