### ISSUE TITLE
when pressing damage from a hidden spell, the spell name is shown

### ISSUE THREAD

**Issue by WooTHaX** [xdy/xdy-pf2e-workbench#702]
When using the QoL setting "cast in private" for spells and using the "post public message that a spell has been cast"
The spell-card is correctly hidden and just a message with some checks are shown to the players.
However, when pressing damage the message includes the spell name. 
(In this example I am also using 'Hide GM rolls')

![image](https://user-images.githubusercontent.com/5989642/225944029-750840a0-5193-4b58-9bea-b7250fa61943.png)

**Comment by joshua-igor** [comment]
![image](https://user-images.githubusercontent.com/19159042/226169306-5320ddd5-6fb2-440d-8ec1-8bce0612027b.png)

Same thing happens even without the module "Hide GM Rolls". It shows a message saying the spell was cast, the attack roll shows just a generic name for the spell, but the damage roll shows the spell's name.

**Comment by xdy** [comment]
Never mind, closed the wrong issue.

**Comment by WooTHaX** [comment]
I am running version 4.56.1 and this issue is still present. 
I still see the spell name when pressing damage as shown in the images before.

I disabled all other modules and created a new actor with spells.
Still shows the spell name for damage.

**Comment by WooTHaX** [comment]
I now see that it looked like the fix broke something and was reverted.
"Turn off trying to hide spell names on damage roll for now as it breaks the chat message. ([a0f6241](https://github.com/xdy/xdy-pf2e-workbench/commit/a0f6241282cbe3df765b8ebe568e6de6bd0bff45))"

So that explains why it is still present.
