### ISSUE TITLE
Wrong variant call for Administer First Aid - Stop Bleeding

### ISSUE THREAD

**Issue by DalvynPF** [xdy/xdy-pf2e-workbench#704]
Clicking on the "Administer First Aid - Stop Bleeding" button in the Basic Action Macros panel gives the following error message:

" Unknown variant 'stopBleeding' used for Administer First Aid, use one of 'stabilize', 'stop-bleeding' "

(Thanks for the module!)

**Comment by xdy** [comment]
This release only fixed it for Skill Actions, next release fixes it for Basic Action Macros.
