### ISSUE TITLE
Dying condition automatically drops off.

### ISSUE THREAD

**Issue by druckle** [xdy/xdy-pf2e-workbench#709]
Something is wrong with the "Manage World Automation Settings" option "Automatically remove Dying when healed to above 0 HP". For some reason this gets triggered even when the token is still at 0.

**Comment by druckle** [comment]
Has not been fixed. Just tested it with new release.
    On Wednesday, March 22, 2023 at 10:30:31 AM PDT, Jonas Karlsson ***@***.***> wrote:  
 
 


Closed #709 as completed via dd8b1f7.

**Comment by xdy** [comment]
Hmm. In that case I need more information so I can reproduce it. Please add screenshots of your workbench settings and detailed reproduction steps.

**Comment by xdy** [comment]
Ah, I think I see. I can reproduce this by - for instance - updating the actor's name.

**Comment by druckle** [comment]
When I reduce a player to 0, the dying condition goes on and the player drops prone. Then immediately it removes the dying condition and adds wounded. 



    On Wednesday, March 22, 2023 at 10:39:16 AM PDT, Jonas Karlsson ***@***.***> wrote:  
 
 


Reopened #709.

**Comment by xdy** [comment]
That just doesn't happen for me. But, I fixed the bug with editing other aspects of an actor making dying drop off, so maybe some variant of that is what happens for you? Try the most recent release.

**Comment by druckle** [comment]
Did you want me to make a login for you on my server?

    On Wednesday, March 22, 2023 at 10:43:27 AM PDT, Jonas Karlsson ***@***.***> wrote:  
 
 


Ah, I think I see. I can reproduce this by - for instance - updating the actor's name.

**Comment by xdy** [comment]
I'm hoping the most recent release (4.52.8) fixed it for you. If it didn't, please try with no other modules but the Workbench active, and if it still fails, add screenshots of your workbench settings in case there's a problem that only occurs with a specific setting combination.

**Comment by druckle** [comment]
Works perfect now! Thank you!
    On Wednesday, March 22, 2023 at 11:18:12 AM PDT, Jonas Karlsson ***@***.***> wrote:  
 
 


I'm hoping the most recent release (4.52.8) fixed it for you. If it didn't, please try with no other modules but the Workbench active, and if it still fails, add screenshots of your workbench settings in case there's a problem that only occurs with a specific setting combination.

**Comment by xdy** [comment]
Nice! Computers can be strange and capricious beasts at times. :)

**Comment by druckle** [comment]
Last night during combat the initiative order kept randomly changing for no known reason. When I changed the "Setting initiative to just before the current combatant: to Never. It stopped.
    On Wednesday, March 22, 2023 at 11:23:00 AM PDT, Jonas Karlsson ***@***.***> wrote:  
 
 


Closed #709 as completed.
