### ISSUE TITLE
Bug: Creature Builder bonuses reporting 0

### ISSUE THREAD

**Issue by TheTenk** [xdy/xdy-pf2e-workbench#716]
issue #705 seems to be back, experienced in v4.54.0 on ForgeVTT

**Comment by xdy** [comment]
Which creature did you scale, and to what level?

**Comment by TheTenk** [comment]
I attempted to create a few level 2 spellcaster NPCs from scratch alongside a level 3 Brute; their AC/HP/Saves/Perception changed appropriately, but it did not output spellcasting/strike/skill numbers except 0s

**Comment by BasiliskOnline** [comment]
Having this problem as well, Workbench v. 4.56. Tried on both forge and my local foundry. Both report +o strike, no damage. no Spell DC or Attack.

Edit: I tried to roll back to another version of workbench, and i went pretty far back and still doesn't work. I'd guess it seems to be a change to the PF2E system?

**Comment by AFigureOfBlue** [comment]
I'm seeing the same bug; and additionally, applying a roadmap doesn't seem to work (it just always leaves everything at moderate, even if I select a roadmap such as "magical skirmisher". PF2 system v 4.10.3, workbench v4.58.1

**Comment by Malkyn99** [comment]
On 4.59.4, issue persists. Turned off all other modules to confirm it's self-contained and not a bad interaction.

**Comment by Serban-AndreiC-2054619** [comment]
Still persisting on 4.64.3. It's such a shame, as I'd love to use this feature to create monsters on the fly.

**Comment by KyloBren** [comment]
I'm on Workbench v4.64.3 and Pf2e System v4.10.3, the issue still persists for me as well.

**Comment by Maelorn09** [comment]
Issue still persists 
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/114569560/556cf012-569d-4abe-aaba-b27d210f683f)

**Comment by xdy** [comment]
I've removed the creature builder as it no longer works, and a viable alternative exists: https://github.com/miki4920/fvtt-module-pf2e-MonsterMaker
