### ISSUE TITLE
Request: Add Option to Make Secret Checks in Basic Action Macros/Recall Knowledge Act Like Normal Secret Rolls

### ISSUE THREAD

**Issue by GorgoPrimus** [xdy/xdy-pf2e-workbench#718]
Basic Action Macros (at least Recall Knowledge, but possibly all the Secret checks) default to making all secret checks super duper secret, such that the result can't be revealed to everyone by the GM afterwards without a full refresh. When I tested it a Recall Knowledge check roll didn't even show a role to the player making it (just an alert messaging telling them they did it), and only the GM could see the roll and result. The only way to show to players at that point is to make the message show to all and have everyone refresh so it shows up in the log.

I'd love an option or setting to make them just normal secret checks where the players see it happen but can't see the result until/unless I reveal it.

**Comment by xdy** [comment]
I think Darkim answered this in discord, either way, I should have gone to bed earlier last night. :)
I.e. I can't actually do anything about this isse, so closing it.
