### ISSUE TITLE
Players can't see Skill Actions

### ISSUE THREAD

**Issue by GlassFedDockterr** [xdy/xdy-pf2e-workbench#723]
As the title says. I am using TokenHUD, and that's the only thing I can think of that could interfere with the action interface on the character sheet.

**Comment by xdy** [comment]
Showing Skill Actions is a client setting. I.e. each user has to set it for themselves. (Or, the gm can enable https://gitlab.com/kimitsu_desu/force-client-settings and/or https://github.com/ironmonk88/monks-player-settings to set things up for all users.)
