### ISSUE TITLE
BUG: Changing the Game Paused text causes call to missing hook, breaking package

### ISSUE THREAD

**Issue by Abourass** [xdy/xdy-pf2e-workbench#762]
As of the update I pulled last week, I'd noticed that the macros and the text changed "Game Paused" text stopped working.

After some investigating, I found that if I removed the custom text, the macros go back to working, as the call to the thrown hook no longer stop the code;

Here's the error:
![image](https://user-images.githubusercontent.com/39917231/233476209-e99c7ec0-6697-4378-9d07-5f6390b1673c.png)

**Comment by xdy** [comment]
Hmm. I can't reproduce on the latest (Workbench 4.63.4, Foundry 291, pf2e 4.10.4), both macros and changing custom text works for me.
Are you also on that version? And, do you have any modules enabled?

**Comment by xdy** [comment]
Haven't heard back, so assume it works now. Closing issue.
