### ISSUE TITLE
MAP buttons stopped working k in BAM

### ISSUE THREAD

**Issue by popydo** [xdy/xdy-pf2e-workbench#773]
Trip (-5) and Trip (-10) does not add the indicated modifiers (they just give basic roll) – and all other (-5) and (-10) buttons (like Disarm etc.) display an error "m.toObject is not a function" and doesn't work at all :(

**Comment by xdy** [comment]
Turned them off for now. Will take a look at this later.

**Comment by Myriade91** [comment]
Any news on that front?

**Comment by xdy** [comment]
Oh, I forgot to close this issue. This was fixed in 4.76.4

**Comment by xdy** [comment]
Though it might not work until the next pf2e release, I was testing on the latest developer version of pf2e.
