### ISSUE TITLE
Recall Knowledge macro rework

### ISSUE THREAD

**Issue by DalvynPF** [xdy/xdy-pf2e-workbench#777]
As suggested on Discord, here's a link to a reworked version of the Recall Knowledge macro that simulates fake rolls in order to get the correct modifier for each skill:

[https://pastebin.com/iZuB3CXt](https://pastebin.com/iZuB3CXt)

(It is an updated version from the first one I posted in Discord.)

**Comment by xdy** [comment]
Closing this as I saw you posted on Symon's repo.
