### ISSUE TITLE
Recall Knowledge?

### ISSUE THREAD

**Issue by ChasarooniZ** [xdy/xdy-pf2e-workbench#780]
Wil lrecall knowledge ever be able to return or is it broken beyond belief?

**Comment by xdy** [comment]
The recall knowledge button on npcs isn't likely to return. I suggest using the Recall_Knowledge macro instead. (It's in the Symon-provided macros compendium, which can also be called from Basic Action Macros which is in the PF2e Workbench Macros compendium.)
