### ISSUE TITLE
Remystify on copy

### ISSUE THREAD

**Issue by yorkshirelandscape** [xdy/xdy-pf2e-workbench#808]
Please consider rerolling the mystification when a token is copied. This might just be me, but I like to lay out my NPCs with notes in the margins of the map, then copy them into the scene from there. As it is, the new copies have the exact same mystified name as the original. I would think that, in the copying use case, wanting a new name would be more common. 

I'm able to affectively achieve this functionality by installing both Workbench and Token Mold, but I'd rather not run Token Mold just for this one little thing and I prefer Workbench's mystification system.

**Comment by xdy** [comment]
That's already a (hidden) feature of mystification. To access it set the following option to ctrl. That way ctrl-v (paste) also counts as 'mystify', which rerolls on the tables.
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/246024/0c72ab02-ac96-4abc-9f41-2156b6d58410)

**Comment by yorkshirelandscape** [comment]
Hah. Nice. Thank you!

**Comment by yorkshirelandscape** [comment]
Oh... slight problem. Doesn't work on Macs. Any thoughts?

**Comment by xdy** [comment]
I don't have a mac so I can't test, but I *think* command is supposed to be the same thing as control on macs. I.e. command-v might work.

**Comment by yorkshirelandscape** [comment]
I already had it set to Ctrl, actually. So if it was going to work, it would have already. I have the same problem with Quick Insert. The default keybinding has to be changed there.

**Comment by xdy** [comment]
I've added support to set the modifier key to Meta/⌘ (command)/⊞ (windows), which *might* make it possible to use command-v to paste and reroll names on macs in version 4.76.0, give it a try!

**Comment by yorkshirelandscape** [comment]
That did it. Thank you for the prompt response!

**Comment by yorkshirelandscape** [comment]
Ahh, sorry. I lied. I forgot to disable Token Mold before testing it. It doesn't actually work.
