### ISSUE TITLE
Bug: Recall Knowledge macro stopped working overnight

### ISSUE THREAD

**Issue by fishrobe** [xdy/xdy-pf2e-workbench#823]
Was working fine yesterday with 0 problems but during the game today it wouldn't work (Me nor any of my players across 2 games). 

 We get the "You need to select exactly one token" message when nothing is selected, but when something is selected, nothing happens. 

f12 shows :
"41617:107 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'filter')
[No packages detected]
    at Macro.eval (eval at _executeScript (foundry.js:20080:16), <anonymous>:107:59)"

Tried rolling back to a previous version of workbench since it just updated, but that wasn't the problem. Any ideas?

**Comment by fishrobe** [comment]
After rolling back both the PF2E System Update and the latest workbench update it works again, so it seems to be some incompatibility /problem with those. (rolling back only one or the other didn't work; it had to be both of them--PF2E Version 4.11.2 and Workbench 4.75.1 for it to work).

**Comment by xdy** [comment]
The macros live over at https://gitlab.com/symonsch/my-foundryvtt-macros/-/tree/main/PF2e so normally an issue there would be better. But, in this case it has already been fixed in that git repo and I just released an update to the Workbench that includes it.
