### ISSUE TITLE
Request: Recall Knowledge Macro Firing Animation

### ISSUE THREAD

**Issue by harrisog** [xdy/xdy-pf2e-workbench#824]
It would be awesome if the Workbench macro would automagically fire the new Recall Knowledge animation, provided those mods are present

**Comment by MrVauxs** [comment]
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/32039708/391a07b4-f8d4-44ec-ae2b-063da6bb6539)

**Comment by harrisog** [comment]
I ended up just copy pasting the brain response animation macro into my locally imported recall_knowledge workbench macro for now, but this method has a couple of drawbacks -- it doesn't work when used via the BAM, and future tweaks to the animation requires manually updating the macro

**Comment by xdy** [comment]
The macro BAM uses is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Recall_Knowledge.js
Not sure who maintains it, but ask about it on https://discord.com/channels/880968862240239708/880969174661353484 or make an issue on Symon's repo.
