### ISSUE TITLE
Request: Chat card collapse should work for players too?

### ISSUE THREAD

**Issue by fraserstanton** [xdy/xdy-pf2e-workbench#85]
Currently is GM only, should be player also (configurable?)

**Comment by xdy** [comment]
Hmm. It works for me. As in, when I log on to a game as a player with that setting enabled it collapses, and I can disable and enable that setting.
A conflict with some other module perhaps?

**Comment by fraserstanton** [comment]
OMG it is player also, that was not obvious to me. Maybe for this indicate which options are both player and GM? Just as a nice to have thingy? Very cool btw. Oh and if you get around to it, an icon in the title bar to indicate it is collapsed would be nice too.
Keep up the good work!

**Comment by xdy** [comment]
I use https://github.com/flamewave000/dragonflagon-fvtt/tree/master/df-settings-clarity to handle this. A module that should really be core imho.
