### ISSUE TITLE
PF2e Target Damage card being "undone" by PF2e Workbench

### ISSUE THREAD

**Issue by Sildamet** [xdy/xdy-pf2e-workbench#860]
Howdy folks. So I'm having an issue when using PF2e Target Damage and PF2e Workbench together, that after I rolled saving throws and damages, the moment I apply the damage to a target the "card" becomes just a regular number and the damage can't be applied to any other target.
Example: This card
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/74163724/fa154efd-5d45-44e7-98f9-d1ebc963bebe)

Turns into this card
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/74163724/cb0430a6-bf0a-4160-bc35-3aaec0b87910)

I wasn't sure to whom I should report the issue, so I decided to report to both creators. :) Thank you for your attention!

**Comment by xdy** [comment]
I assume you have "Check to hide the name of a privately cast spell." enabled? If so, disable it.
This bug is the reason that feature is experimental. It somehow sometimes wrecks messages, and I haven't yet been able to figure out what is going on.

**Comment by Sildamet** [comment]
It was _exactly_ that. Will keep it off and try again when a new version pops out. Thank you for your, as usual, prompt response.

Have a great day, and thank you for the wonderful module.

**Comment by Sildamet** [comment]
(not sure if you want to keep the issue open as a reminder or not, that's why I did not close it yet.

**Comment by xdy** [comment]
This should be fixed in Workbench 5.2.0
