### ISSUE TITLE
"Do not disable item bonuses when using ABP" option not working

### ISSUE THREAD

**Issue by dmpunks** [xdy/xdy-pf2e-workbench#861]
This does not seem to be working for me in FoundryVTT 11.302 with Pathfinder 2nd Edition 5.0.2 and PF2e Workbench 5.0.3.

Tests done:

TEST 1: Verify that item bonuses are getting added to rolls:
- set PF2E system option "Automatic Bonus Variant Rules" to "Do not use ABP"
- Roll Treat Wounds while Healer's Tools (Expanded) is equipped
Expected and Actual Result: +1 item bonus is added

TEST 2: Turn on ABP
- set PF2e system option to "ABP: Allow property runes"
- enable workbench option "Do not disable item bonuses when using ABP"
- Roll Treat Wounds while Healer's Tools (Expanded) is equipped
Actual result: no item bonus is added to the roll
Expected result: +1 item bonus is added

Thanks in advance!

**Comment by xdy** [comment]
Unfortunately I can't figure out how to fix it, so I'm removing this feature. I recommend you instead use https://github.com/reonZ/pf2e-toolbelt/#automatic-rune-progression-requires-reload to handle ABP.

**Comment by xdy** [comment]
Unfortunately I can't figure out how to fix it, so I'm removing this feature. I recommend you instead use https://github.com/reonZ/pf2e-toolbelt/#automatic-rune-progression-requires-reload to handle ABP.
