### ISSUE TITLE
Request: Aura of Despair

### ISSUE THREAD

**Issue by tgog217** [xdy/xdy-pf2e-workbench#862]
Add the following:

Aura of Despair (Aura)

{"effects":[{"affects":"enemies","events":["enter"],"uuid":"Item.5CPQ6G4BUgHxko14"}],"key":"Aura","radius":"15","slug":"aura-of-despair"}

Aura of Despair (Effect)

{"key":"ActiveEffectLike","mode":"add","path":"flags.xdy-pf2e-workbench.condition.frightened.min","value":1}

Item.5CPQ6G4BUgHxko14 referring to the effect. No idea how submit code but figured this would be a good addition.

**Comment by xdy** [comment]
Done (somewhat differently) in Workbench 5.3.0
