### ISSUE TITLE
Basic Action Macro - Demoralize with Assurance (Intimidation)

### ISSUE THREAD

**Issue by Suldrun45** [xdy/xdy-pf2e-workbench#864]
Hello,
My character has the Assurance feat for the Intimidation skill.
When I use Demoralize from the Basic Action Macro, I don't get the option to use Assurance
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/49712710/df2a7a70-824c-4d22-a636-846ba652c761)

The option appears normaly when I use the Intimidation skill or the Demoralize action directly from the character sheet.
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/49712710/271899a1-11db-4b76-9ae5-a9dcc0466414)

I'm on v11 with latest version of Foundry, PF2e and Workbench (5.1.0)

**Comment by xdy** [comment]
It uses the macro from here: https://gitlab.com/symonsch/my-foundryvtt-macros/-/tree/main/PF2e/Contributions%20by%20others which does not handle assurance.
