### ISSUE TITLE
If Simple Calendar is enabled, persistent damage checks are rolled twice and applied twice.

### ISSUE THREAD

**Issue by WaterpoloBlock** [xdy/xdy-pf2e-workbench#868]
Foundry Version: V10
Build: 291
Pf2e version: 4.12.9

Active Modules (3):
PF2e WorkBench
Simple Calendar
The Forge

If the following is enabled:
- Automatically apply persistent damage and recovery roll
- Simple Calendar is enabled

For whatever reason, it'll make the recovery check twice, and apply the damage twice.

I'm not sure what's going on, this was working fine last week. I only noticed it today.

![Test_Image](https://github.com/xdy/xdy-pf2e-workbench/assets/73310678/5e66a135-6641-4fe8-9362-009c14fa3a22)

**Comment by WaterpoloBlock** [comment]
Also occurs during recovery checks for dying.

**Comment by WaterpoloBlock** [comment]
Issue still occurs in:
V11
Build 304
Pf2e: 5.1.0

**Comment by ottyn** [comment]
Also starts the Hero Point Handler twice if you have it auto-start enabled.  Only happens with Simple Calendar installed.

**Comment by xdy** [comment]
The problem started with SC 2.3.0 (i.e. this commit https://github.com/vigoren/foundryvtt-simple-calendar/commit/17f8d1a0bae3d8d405ca7bb0414af5dd67de0eea#diff-99e0cad08483cc695cce6acb842cb37657e39bccf77ac3f7970c0ee42efbbd35)
If I roll back to SC 2.2.0 it works.
It's probably some interaction with SC's hooks for createChatMessage/renderChatMessage and the same for the workbench.
Beyond that, not a clue.
