### ISSUE TITLE
Aura of Despair: Minimum Frightened Effect applies Frightened 1 to every enemy

### ISSUE THREAD

**Issue by elemorelli** [xdy/xdy-pf2e-workbench#873]
When an actor has the Aura of Despair, the Minimum Frightened Effect is automatically giving Frightened 1 to enemies.

I really like that it prevents the automation to reduce it, but I don't think it should automatically give conditions.

Please, see the video below:

https://github.com/xdy/xdy-pf2e-workbench/assets/1661552/cca92dea-f90a-4a8f-a314-6f9cc0575752

**Comment by xdy** [comment]
Hah. Yeah. You're absolutely right. I based it on Dirge of Doom and forgot to remove Frightened. Will be fixed in next release.

**Comment by elemorelli** [comment]
Amazing! Thanks a lot! 😄
