### ISSUE TITLE
RequestChecksMenu macro doesn't work if no DC supplied

### ISSUE THREAD

**Issue by kjaranso** [xdy/xdy-pf2e-workbench#876]
When using the RequestChecksMenu macro, if you select a check, it gives a prompt saying:
"If the DC is invalid or left blank, then a Check with no listed DC will be posted."
<img width="206" alt="image" src="https://github.com/xdy/xdy-pf2e-workbench/assets/128510187/d6d5dd0d-a650-462f-8446-33d755ba678b">

However, if you leave it blank or enter an invalid DC, it will give you an error.

I think it makes sense to give an error if you supply a bad DC, but I like to be able to post a check for the players without telling them the DC at times.

**Comment by xdy** [comment]
That macro lives on Symon's repository (https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/RequestChecksMenu.js), I just include it in the Workbench for convenience. Ask about on the pf2e discord, or make an issue on Symon's repo above. If someone fixes this it will automatically be included in the next release of the Workbench and thus updated in your world.
