### ISSUE TITLE
Automatically Apply Persistent damage no longer works

### ISSUE THREAD

**Issue by WaterpoloBlock** [xdy/xdy-pf2e-workbench#877]
This ticket is a follow up to this [ticket](https://github.com/xdy/xdy-pf2e-workbench/issues/868)

V11
Build 304
Pathfinder 2e (5.1.0)

2 Modules:
Work Bench (5.4.2)
The Forge (1.10)

Browser: Chrome

When testing the automation features. The system appears unable to apply the persistent damage at all.

![Apply_Persistant_Damage](https://github.com/xdy/xdy-pf2e-workbench/assets/73310678/7f8752ad-a19e-49e9-8fa7-3d2a8576c496)

Also, the original issue for ticket #868  still remains.
The only difference now, is that persistent damage is no longer rolled at all when Simple Calendar is enabled.

I also noticed this error pop up when making a Death recovery check with Simple Calendar enabled.

![Death_Save](https://github.com/xdy/xdy-pf2e-workbench/assets/73310678/f492cb50-f927-497c-bbdc-52c768037337)

For what it's worth, I did create a ticket with the devs for Simple Calendar. Right [here](https://github.com/vigoren/foundryvtt-simple-calendar/issues/515)

**Comment by xdy** [comment]
Oh bother. I've fixed so it works without Simple Calendar at least.

**Comment by WaterpoloBlock** [comment]
> Oh bother. I've fixed so it works without Simple Calendar at least.

With the ticket I made for Simple Calendar. It looks like one of the devs know what the bug is and will get it fixed in a few days. So fingers crossed.

**Comment by WaterpoloBlock** [comment]
[After the ticket](https://github.com/vigoren/foundryvtt-simple-calendar/issues/515) I tested out the feature. It appears to be working now:
Recovery roll (For dying and persistent damage) is only rolled once.
Result of Recovery while dying is only applied once. And damage roll for Persistent damage is only applied once.

I’d say confirm it for yourself. Otherwise, you can close the ticket. And I apologies for the wild goose chase. I should have opened a ticket with the simple calendar devs first.
