### ISSUE TITLE
"Sort actions by name when the actor sheet is opened" doesn't work

### ISSUE THREAD

**Issue by Vesselchuck** [xdy/xdy-pf2e-workbench#881]
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/70449411/18505e3b-d2fe-4146-a221-e4a04716fa44)
Doesn't even open character sheet. Works absolutely fine with the aforementioned setting turned off.

FVTT v11.305
PF2e v5.1.1

**Comment by xdy** [comment]
This was fixed in Workbench 5.4.4
