### ISSUE TITLE
NPC Mystifier being applied to PCs

### ISSUE THREAD

**Issue by elemorelli** [xdy/xdy-pf2e-workbench#89]
Hi!

I'm having an issue with the NPC Mystifier turned on by default: It's also being applied to PC tokens when I place them on the map.
Is there any way to disable the NPC Mystifier for PCs or Linked tokens?
I know Token Mold has an option to skip linked tokens. Maybe it's possible to make something similar?

And tThanks for the awesome work on this module! :D

**Comment by xdy** [comment]
Yeah, my players have complained about being renamed to things like 'Unknown Human Humanoid 42' a couple of times, but, I always forget to fix it. So, my players thank you for reminding me about this. :)
I think I'll have it skip all actors that have a player owner.
