### ISSUE TITLE
compendiums disappeared with newest update

### ISSUE THREAD

**Issue by WizardForHire123** [xdy/xdy-pf2e-workbench#901]
lost compendium macros in recent update.

**Comment by xdy** [comment]
Hmm. Works on my machine.
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/246024/4a002dab-0574-4e93-ab46-952d1b47492c)

**Comment by xdy** [comment]
Also works on the forge, but do note that your world needs to use the latest of both foundry (11.306) and pf2e (5.2.1) to be able to install the latest workbench.
