### ISSUE TITLE
Treat Wounds modifier in the BAM UI should account for Natural Medicine

### ISSUE THREAD

**Issue by venom986** [xdy/xdy-pf2e-workbench#902]
The modifier displayed for Treat Wounds in the BAM UI does not use the Nature skill modifier in place of the Medicine modifier when the selected character has the Natural Medicine feat, but it should.

**Comment by xdy** [comment]
The macro BAM uses is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Treat%20Wounds%20and%20Battle%20Medicine.js
Ping darkim about it on https://discord.com/channels/880968862240239708/880969174661353484 or make an issue on Symon's repo.
