### ISSUE TITLE
Skill Actions not appearing on player sheets

### ISSUE THREAD

**Issue by dootxdoot** [xdy/xdy-pf2e-workbench#908]
Title issue - also had my players go through settings and set actions to appear on their sheet. They refreshed into it and it's still not working.

**Comment by xdy** [comment]
Hmm.  Works on my machine:
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/246024/3aecd92e-502a-4443-9c9c-08ec757c4df9)

![image](https://github.com/xdy/xdy-pf2e-workbench/assets/246024/2f185de3-bbb4-4fc4-a8b2-a9d655b5c159)

![image](https://github.com/xdy/xdy-pf2e-workbench/assets/246024/b5193af1-2c2f-4079-9598-0396905eb4ac)

Try if it works with no other modules active.
Do you get any errors (red text) in the console?

**Comment by dootxdoot** [comment]
I personally can see the actions on my players' sheets but when they do it they are unable to.

Here is what I see.
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/70672768/3439fa75-20f6-4019-a30e-b179ab731c13)


Here is what my players' see.
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/70672768/e28fcc64-2b5c-4533-8803-56496999dc1e)


I verified no red text in console.

Verified skill actions was working as checked as well on player side.

**Comment by dootxdoot** [comment]
I did get a pop up I've never seen before, unsure if it is related.

Seems like I'm probably doing something wrong on my end.

![image](https://github.com/xdy/xdy-pf2e-workbench/assets/70672768/a50f857d-c3e1-493e-adf9-dfef7c166d9d)

**Comment by Chesire** [comment]
@dootxdoot I had a similar issue today, My player sheets had no actions, and I couldn't see much PF2E content at all (no weapons, armor, items etc). I uninstalled the PF2E system and reinstalled it and all the actions then appeared in my character sheets. Might work for you?

**Comment by Ratfink23** [comment]
I am having the same issue - I can see the Skill Actions tab but my players can not.

I have tested on a new world with only workbench module enabled and still, the player can not see the Skill actions. 

Foundry V11 306 - PF2e 5.2.3

**Comment by xdy** [comment]
I just tried again in a new world on my machine and could get it to work as both gm and player.
Assuming that a hard reload (ctrl f5) on both sides - after making sure the setting is on - doesn't help, for those with the problem it's certainly worth a shot to try to reinstall both workbench and the system. As foundry doesn't check that downloads succeeded corrupted downloads do occasionally cause all sorts of strange problems.

**Comment by Ratfink23** [comment]
Reinstalled both System and Workbench without fix to the issue. - I will continue to test when I can.

I am running on a remote server on the NodeJS build. I will try on a local windows install and see if that changes anything.

**Comment by Ratfink23** [comment]
I have found that it works if the players activate it they can see it for their character, but it doesn't work as a global setting.

**Comment by xdy** [comment]
Ah, I see. The setting is a client setting, so each user has to set it for each browser they use. (Unless the GM force sets it using a module like https://gitlab.com/kimitsu_desu/force-client-settings).
So, closing issue as it is working as intended.
