### ISSUE TITLE
"Update Aura Radius" macro doesn't update aura animations

### ISSUE THREAD

**Issue by LonePaladin** [xdy/xdy-pf2e-workbench#951]
When I place a spell that creates an expanding emanation -- such as Bane and Bless -- Automated Animations catches that and places a 5-foot radius animated aura around the selected token. The Workbench macro that also triggers adds a condition for tracking the size; you can left-click on it to make it larger, or right-click to make it smaller.

Problem is, changing the size doesn't change the animation. Even if you've expanded it to a 20-foot radius, the animation is still locked at 5 feet. The *effect* works, creatures that are in range get affected by it, but the *visual cue* isn't getting bigger.

I asked about this on the Discord server for JB2A/PF2E Animations, and MrVauxs told me the "Update Aura Radius" macro is supposed to address this -- but it doesn't.

**Comment by xdy** [comment]
See https://github.com/xdy/xdy-pf2e-workbench/issues/913
Closing issue.
