### ISSUE TITLE
Demoralize Macro ignores some modifiers to target's DC

### ISSUE THREAD

**Issue by Cuingamehtar** [xdy/xdy-pf2e-workbench#957]
Example: when trying to Demoralize an elf character with Forlorn feat, the macro calculates target's DC without adding +1 circumstance bonus from Forlorn.

**Comment by xdy** [comment]
This macro is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Demoralize.js
Not sure who maintains it, but ask about it on https://discord.com/channels/880968862240239708/880969174661353484 or make an issue on Symon's repo.
