### ISSUE TITLE
[Feature Request] Use higher of potency or item bonus

### ISSUE THREAD

**Issue by AFigureOfBlue** [xdy/xdy-pf2e-workbench#962]
I'm so glad this module adds in the "Do not disable item bonuses when using ABP" option. I use a variant of ABP, where the higher of an item bonus or potency bonus is what gets used (this way, mutagens and the like are still useful, but without stacking with ABP's potency bonuses and causing the numbers to go beyond the bounds of the PF2's expectations). Right now I'm using the option provided by that checkbox, but I still end up needing to manually account for certain things; e.g., I don't want the item bonus to unarmed attacks granted by a _bestial mutagen_ to stack with ABP's potency bonus - I just want the higher of the two to be applied.

I'm not sure if adding an option for this sort of thing is within the scope of this module (or if it's possible in the first place), but I figured it wouldn't hurt to ask seeing as this is where the "Do not disable item bonuses when using ABP" option comes from and this is similarly an adjustment to ABP.

**Comment by xdy** [comment]
Afraid not, my solution isn't particularly flexible.
Using https://github.com/reonZ/pf2e-arp might work ok for you if you haven't tried it already.

**Comment by AFigureOfBlue** [comment]
Thank you for the link! I'll take a look into that module.
