### ISSUE TITLE
Hero Points max out at 3 in PF2 foundry v11 no matter what is set in PF2E Workbench

### ISSUE THREAD

**Issue by Itsadreamtocode** [xdy/xdy-pf2e-workbench#973]
Since upgrading to Foundry v11 and the latest version of PF2E engine, the max hero points do not allow for more than 3. Note: I have not tested less than 3 max, but may be broken as well.

PF2E engine: 5.4.1, and 5.4.2 
PF2E Workbench: 5.18.1
Foundry version: v11 stable 308

Images of what I set it to, and a character immediately after with 3 hero points max. You can also see the foundry version
![image_720](https://github.com/xdy/xdy-pf2e-workbench/assets/89952722/220b5717-01ca-4501-9d2f-5dc91a7a3909)
![image_720](https://github.com/xdy/xdy-pf2e-workbench/assets/89952722/dadc2122-d6f9-40dd-95a1-6d66c602f1e7)

**Comment by xdy** [comment]
Don't really see a decent way of fixing this, so I'm removing this feature and suggesting you use this Rules Element solution instead (i.e. add this RE to a permanent item on each character after changing 20 to whatever value you want to use for max hero points):
```json
{
  "key": "ActiveEffectLike",
  "mode": "override",
  "path": "system.resources.heroPoints.max",
  "value": 20
}
```
Taken from https://discord.com/channels/880968862240239708/880969253765935174/1146996538023878676
