### ISSUE TITLE
"Update Aura Radius" macro does not update linked animations

### ISSUE THREAD

**Issue by LonePaladin** [xdy/xdy-pf2e-workbench#977]
This is [the issue I posted in the JB2A Macros GitHub](https://github.com/MrVauxs/pf2e-jb2a-macros/issues/157), they referred me to your macro. When I create an aura spell (like Bane or Bless), it creates an aura around the token linked to a 'condition' that you can increase or decrease to change the size of the emanation. With PF2E Animations, it creates an animation within that area, but if you increase the size of the aura the animation doesn't change to match. I was told that the Workbench has an "Update Aura Radius" macro that manually fixes this, but running the macro has no visible effect.

**Comment by xdy** [comment]
This macro is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Update%20Aura%20Radius.js
Ping JDCalvert about it on https://discord.com/channels/880968862240239708/880969174661353484 or make an issue on Symon's repo.
