### ISSUE TITLE
[BUG] Skill actions expanding topwards instead of downwards

### ISSUE THREAD

**Issue by sorrythatuserbla** [xdy/xdy-pf2e-workbench#983]
Skill Actions added by Workbench open UP on the character sheet.  Other Actions still open DOWN.
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/78597675/ebba4b29-6451-445c-b5ae-40d5f0554ddd)

**Comment by King-Wedgie** [comment]
Yeah I came here to report this same issue; been like this for a bit and it throws me off every time.

**Foundry** v11.309
**PF2E** 5.6.1
**Workbench** 5.18.3
