### ISSUE TITLE
[Feature Enhancement] - Allow repair of constructs (actors)

### ISSUE THREAD

**Issue by bucket-au** [xdy/xdy-pf2e-workbench#985]
Constructs should be able to be repaired using a repair action, essentially cure wounds but for constructs. 
Currently you are prompted to drag an item into a dialog with no way to apply to an actor.

**Comment by xdy** [comment]
This macro is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Repair.js
Ping darkim about it on https://discord.com/channels/880968862240239708/880969174661353484 or make an issue on Symon's repo.
