### ISSUE TITLE
Battle Medicine/Treat Wounds healing healing roll seems to sometimes queue up

### ISSUE THREAD

**Issue by dtread14** [xdy/xdy-pf2e-workbench#989]
This only seems to happen when I'm on a server I don't own. When a battle medicine or treat wounds roll is made, the healing roll doesn't immediately trigger.  Instead, after rolling another battle medicine or treat wounds, both healing rolls are then triggered.
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/120229323/0ca2ad94-0ae5-47e0-90f2-6fd64711e542)

**Comment by xdy** [comment]
This macro is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Treat%20Wounds%20and%20Battle%20Medicine.js
Ping darkim about it on https://discord.com/channels/880968862240239708/880969174661353484 or make an issue on Symon's repo.
