### ISSUE TITLE
Shifting Rune Macro broken

### ISSUE THREAD

**Issue by mereghost** [xdy/xdy-pf2e-workbench#991]
Weaponshifiting seems to have become broken recently.

The error I'm getting is 

`Uncaught (in promise) TypeError: weaponToShift.system.preciousMaterial is undefined`

**Comment by xdy** [comment]
This macro is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/weaponshifting.js
Post about it on https://discord.com/channels/880968862240239708/880969174661353484 or make an issue on Symon's repo if it hasn't already been fixed (I think it may have, I saw a commit by Symon about a week ago.)
