### ISSUE TITLE
Treat Wounds and Ward Medic Interaction

### ISSUE THREAD

**Issue by WraithJT** [xdy/xdy-pf2e-workbench#997]
If a character does not have at least Trained proficiency in Medicine and has the Ward Medic feat (a Chirurgeon Alchemist, for example), and attempts to use the Treat Wounds macro from the Basic Actions Macro, it presents an error "Too many targets (1) for Treat Wounds. You can select a maximum of 0.5 targets."

**Comment by xdy** [comment]
This macro is not maintained by me, I only include it from from Symon's git repo at https://gitlab.com/symonsch/my-foundryvtt-macros/-/blob/main/PF2e/Contributions%20by%20others/Treat%20Wounds%20and%20Battle%20Medicine.js
Ping darkim about it on https://discord.com/channels/880968862240239708/880969174661353484 or make an issue on Symon's repo.
