### ISSUE TITLE
[Module addition] Cracks Bonus Progression (Another Alternative Bonus Progression)

### ISSUE THREAD

**Issue by NotReallyACat** [xdy/xdy-pf2e-workbench#999]
I have made an alternative effect inspired by the ABP variant rule and ARP module.

---
**Description**
This is a houserule variant of Automatic Bonus Progression and Automatic Rune Progression. This replaces fundemental runes.

  | +1 | +2 | +3
-- | -- | -- | --
Weapon Attack Bonus | L2 | L10 | L16
Magic Attack Bonus | L3 | L11 | L17
Damage Dice Bonus | L4 | L12 | L19
Armor Class Bonus | L5 | L11 | L18
Saving Throw Bonus | L8 | L14 | L20

The table shows the bonus progression along with level you get each bonus. This replaces Armor, Resilient, Weapon and Striking runes. It also increases spell attack rolls.

---

Effect:
[AABP.zip](https://github.com/xdy/xdy-pf2e-workbench/files/12712115/AABP.zip)

It needs an image I may make one but anything will do, the feat item will need linking to the effect.
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/49882452/49099cfb-1e86-4a1a-8c68-302cc6533473)
![image](https://github.com/xdy/xdy-pf2e-workbench/assets/49882452/1ec0b64e-3d01-440e-acd3-4b355dd78b05)

**Comment by xdy** [comment]
Included in the latest release, with a quick icon from fontawesome.
